-- pet: 69 products

INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Nestl Dessert Noir 53% cacao', 'Nestl Dessert Noir 53% cacao', 'pet', '', '', '', 0, 'Nestl', 'openpetfoodfacts', 'unisex', 'pet'),
  ('pedigree biscotti multi mix', 'Biscotti croccanti. Multi-mix - gusti di pollo, manzo e agnello. Alimento complementare per cani adulti.', 'pet', 'Cereali, carni e derivati (di cui 1% di pollo nel biscotto bianco, 1% di manzo nel biscotto marrone e 1% di agnello nel biscotto rosso), sottoprodotti di origine vegetale, oli e grassi, sostanze minerali.', 'Cereali', '', 0, 'PEDIGREE', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Friandises au poulet pour chat et chaton', 'Croquettes', 'pet', 'C r ales, Sous-produits d''origine v g tale, huiles et graisses, viandes et sous-produits animaux (dont poulet 4%), extraits de prot ines v g tales, substances min rales.', 'C r ales', '', 0, 'Catisfactions', 'openpetfoodfacts', 'unisex', 'cat'),
  ('speed 250 ml', 'speed 250 ml', 'pet', 'carbonated water, sugar, acidity regulator (330), stabilizer (414), preservative (211), caffeine, added flavors (natural, nature identical and artificial flavoring substances)', 'carbonated water', '', 0, NULL, 'openpetfoodfacts', 'unisex', 'pet'),
  ('Chats st rilis s adultes', 'Chats st rilis s adultes', 'pet', 'Sau hydrat es de volaille, mais olenes d shydrat es de ba Betterave graisse animale, sel DDITIPS/kg. Additifs nutritionnels amine E 460 mg Vitamine Conopr BRE ELABOR POUR LES 6 proteine de mais, proteines ot ines deshrat es de porc amine D3 21300 com/sodium Pyridoxine 50mg, Taurine 1400 mg L-carnitine 500g Vitamine B6 ( 8,3 g Sulfate ferreux monohydrat 356 mgmg) indure de pose 1.2 mg, Sulfate de cuivre pentahydrat 45 mg (Cu 12 maj ele de man monohydrate 168 mg (Mn. 55 mg). Sulfate de zinc monohy', 'Sau hydrat es de volaille', '', 0, 'Ultima', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Croquettes Pour Chat Adulte St rilis Boeuf Bifensis', 'Bifensis PURINA ONE', 'pet', 'Abats de b uf 16%, Prot ines de volaille d shydrat es, Bl 14%, Farine de soja, Ma s, Gluten de ma s, Graisses animale, Gluten de bl , Pulpe de betterave d shydrat e, Racine de chicor e s ch e 2%, Fibres v g tales s ch es, Substances min rales, Hydrolysat, Levures', 'Abats de b uf 16%', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Ananas Boisson saveur', 'Ananas Boisson saveur', 'pet', 'saveur ananas (e330), citron.', 'saveur ananas (e330)', '', 0, 'Laiko', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Eau vertueuse', 'Eau vertueuse', 'pet', '', '', '', 0, 'Velleminfroy', 'openpetfoodfacts', 'unisex', NULL),
  ('Croquettes pour chats', 'Croquettes pour chats', 'pet', '', '', '', 0, 'ULTIMA', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Purina One', 'Purina One', 'pet', '. En utilisant des assimilation optimale des nutriments. Information importante: le paquet de croquettes en format 9,75 kg vous est propos dans un design diff rent de votre produit habituel. Nous vous garantissons cependant qu''il s''agit bien des m mes croquettes et que leur qualit reste inchang e. Caract ristiques des croquettes PURINA ONE pour chat: Bifensis Dual Defence: formule double d fense qui contribue am liorer le bien- tre du chat, l''int rieur comme l''ext rieur. Action cliniquement prou', '. En utilisant des assimilation optimale des nutriments. Information importante: le paquet de croquettes en format 9', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Perfect Fit', 'Perfect Fit', 'pet', '', '', '', 0, 'Mars', 'openpetfoodfacts', 'unisex', NULL),
  ('Cat snacks', 'Cat snacks', 'pet', 'viandes et sous produits animaux, poissons et sous-produits de poisson (6% de saumon), sous-produits d''origine v g tale, lait et produits de laiterie, insuline (0,1%)', 'viandes et sous produits animaux', '', 0, 'Coshida', 'openpetfoodfacts', 'unisex', 'pet'),
  ('carotte', 'carotte', 'pet', '', '', '', 0, NULL, 'openpetfoodfacts', 'unisex', 'pet'),
  ('Whiskas p t chat', 'Whiskas p t chat', 'pet', '', '', '', 0, 'whiskas', 'openpetfoodfacts', 'unisex', 'cat'),
  ('supports whole body healt, adult 1+', 'supports whole body healt, adult 1+', 'pet', '', '', '', 0, 'perfect Fit', 'openpetfoodfacts', 'unisex', 'pet'),
  ('MARKIES ORIGINAL', 'MARKIES ORIGINAL', 'pet', '', '', '', 0, 'PEDIGREE', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Felix Party Mix Original', 'Felix Party Mix Original', 'pet', '', '', '', 0, 'Felix', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Sheba - Saveurs Oc anes Avec Des Mini-filets', 'Sheba - Saveurs Oc anes Avec Des Mini-filets', 'pet', 'Constituants mati res grasses: 4.5; mati re inorganique: 2; cellulose brute: 0.3; humidit ''. 82. Additifs par kg: Additifs nutritionnels:.lodate Sulfate de cuivre pentahydrat : 5,1 mg, Sulfate de fer monohydrate 37.3 mg, Sulfate de mangan se monohydrat : 7 mg, Sulfate Monogehydrateerd A utiliser de pr f rence avant let voir de lot, num ro d''identification usine: voir sur les Houdbaarheidsdatum: zie zijde, Lotnummer, zie individuele verpakking.', 'Constituants mati res grasses: 4.5', '', 0, 'Sheba', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Croquettes pour chat', 'Croquettes pour chat', 'pet', '', '', '', 0, 'Purina One', 'openpetfoodfacts', 'unisex', 'cat'),
  ('croquettes chiens purina', 'croquettes chiens purina', 'pet', '', '', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Gourmet Mousseline au Poulet', 'Gourmet Mousseline au Poulet', 'pet', '', '', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat'),
  ('HERBE A CHAT', 'HERBE A CHAT', 'pet', '', '', '', 0, 'Catisfactions', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Comida gato esterilizado light con pollo, frutas y verduras', 'Comida gato esterilizado light con pollo, frutas y verduras', 'pet', '', '', '', 0, 'Compy', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Friskies 5 promesses b uf poulet', 'Friskies 5 promesses b uf poulet', 'pet', 'C r ales, Viandes et sous-produits animaux (20%, dont boeuf 2% et poulet 2% dans les croquettes en forme de cube 1 ), Extraits de prot ines v g tales, Sous-produits d''origine v g tale, Huiles et graisses, Substances min rales, Levures, L gumes (0,6% de l gumes s ch s, quivalent 4% de l gumes r hydrat s dans les croquettes rondes 2 ) 1 Contenu total dans le produit: 1,6% de b uf et 1,6% de poulet. 2 Contenu total dans le produit: 0,6% de l gumes r hydrat s. Composition type: 80% de croquettes en ', 'C r ales', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat'),
  ('kitten 12mois', 'kitten 12mois', 'pet', 'Prot ines do volaille d shydrat es, nz, isolat de prct res v g tales'', graisses animales, mais, gluten de mais, hydrolysat de animalcs, fibres v6g6talcst pulpe do bottorave, levures et de huile de poisson, sels min raux, huile do sqa, et graires (05 0%), fructod19 saccharidos (0,38 %), hydrdysat de bvure dipsaccharides), extrait do rose d''inde (source M ine), ADD(TIFS (au kg) : AddrtJ nutrrtmnels: Vitamine A: UI, Vitamim 03: 300 UI, E. El (Fer) : 40 mg, E2 (Iode) : 4 mg, E4 (CuiTe) : 12 E5 (Mav ', 'Prot ines do volaille d shydrat es', '', 0, 'Royal canin', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Royal Canin Regular sterilized 37 2kg', 'Royal Canin Regular sterilized 37 2kg', 'pet', 'Proteine di pollame disidratate, mais, glutine di frumento*, fibre vegetali, grassi animali, proteine animali idrolizzate, riso, frumento, polpa di barbabietola, glutine di mais, prodotti del lievito, sostanze minerali, olio di pesce, fruttoligosaccaridi, olio di soia. Vitamina A: 19000 UI, Vitamina D3: 1000 UI, Ferro (3b103): 31 mg, Iodio (3b201, 3b202): 3,1 mg, Rame (3b405, 3b406): 9 mg, Manganese (3b502, 3b504): 40 mg, Zinco (3b603, 3b605, 3b606): 94 mg, Selenio (3b801, 3b811, 3b812): 0,05 mg', 'Proteine di pollame disidratate', '', 0, 'ROYAL CANIN', 'openpetfoodfacts', 'unisex', 'cat'),
  ('150G Fun Tastix Jambon / Fromage Fido', '150G Fun Tastix Jambon / Fromage Fido', 'pet', 'Aliment compl mentaire 1'' pour chiens adultes. osition : C r ales, extraits de prot ines e g yc rol, sucres, viandes et sous produits t fhUites et graisses, substances min rales, ait et produits de laiteric ''drc de fromage * quivalent age blanc s : Additifs nutritionnels : UI/ g : Vit : 9800 ; 660 ; Vit E : 66 ; myag'': Iodate de calcium : 2,5 ; Sulfata ln&lt;cncux monohydrat : 14,3 ; de zjlcmonohydraf : 325 ; S l nite de sodium : l fs scnsoriclr mg/kg : ar me bacon : 3500. et co orants. 1 :nants', 'Aliment compl mentaire 1'' pour chiens adultes. osition : C r ales', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Whiskas sec st rilis au saumon 1 an et +', 'Whiskas sec st rilis au saumon 1 an et +', 'pet', 'c r ales (dont bl 4%), viandes et sous produits animaux, sous-produits d''origine v g tale (dont pulpe de betterave d shydrat e 2%), huiles et graisses, substances min rales, poissons et sous-produits de poissons (dont saumon 4% dans les croquettes marrons clair), extraits de proteines vegetales, legumes (dont carottes d shydrat es 0,5% (equivalent 4% de carottes) dans les croquettes oranges et petits pois d shydrat s 1% ( quivalent 4% de petits pois) dans les croquettes vertes) lrd croquettes ma', 'c r ales (dont bl 4%)', '', 0, 'whiskas', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Dentalife Daily Oral Care Treats', 'Dentalife Daily Oral Care Treats', 'pet', '', '', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Whiskas au thon', 'Aliment complet pour chats adultes', 'pet', 'C r ales, viandes et sous-produits animaux, extraits de prot ines v g tales, huiles et graisses (dont huile de poissons 0,25%, huile de tournesol 0,1%), substances min rales (dont tripolyphosphate de sodium 0,2%), sous-produits d''origine v g tale, poissons et sous-produits de poissons (thon 4% dans les croquettes marron clair), l gumes (carottes 4% dans les croquettes orange, petits pois 4% dans les croquettes vertes).', 'C r ales', '', 0, 'Waltham, Whiskas', 'openpetfoodfacts', 'unisex', 'cat');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Pure Taste', 'Croquettes chien', 'pet', 'Viande de poulet 26%, Viande de poulet fra che 25%, flocons de pommes de terre, farine de pommes de terre, graisse de volaille 5%, carottes 4%, pulpe de betterave sucri re, hydrolysat de foie de volaille 2%, substances min rales, graines de lin 1%, chicor e 1%, levures 0.2% (B-Glucane 0.05%, Mannan-Oligosaccharides 0.04%).', 'Viande de poulet 26%', '', 0, 'Orlando', 'openpetfoodfacts', 'unisex', 'cat'),
  ('plenima sans c r ales ajout es', 'plenima sans c r ales ajout es', 'pet', 'poulet frais 20% , pois, prot ines de poulet d shydrat es 18% , prot ines animales d shydrat es, graisse de volaille, amidon de pomme de terre, prot ines de volaille hydrolis es, min raux, prot ines de volailles d shydrat es, huile de poisson, graines de lin, pommes d shydrat es, carottes d shydrat es, brocolis d shydrat s, canneberges d shydrat es.', 'poulet frais 20%', '', 0, 'Marque Rep re', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Filets Les Effil s de Poulet', 'Filets Les Effil s de Poulet', 'pet', 'Kipfilet (37%), tapiocazetmeel.', 'Kipfilet (37%)', '', 0, 'Sheba', 'openpetfoodfacts', 'unisex', 'pet'),
  ('junior', 'junior', 'pet', '', '', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat'),
  ('micho p te pour les chats', 'micho p te pour les chats', 'pet', '', '', '', 0, NULL, 'openpetfoodfacts', 'unisex', 'cat'),
  ('purina One bifensis sterilcat', 'purina One bifensis sterilcat', 'pet', '', '', '', 0, NULL, 'openpetfoodfacts', 'unisex', 'cat'),
  ('Cat nibbles', 'Cat nibbles', 'pet', '', '', '', 0, 'Cowhide', 'openpetfoodfacts', 'unisex', 'cat'),
  ('snack gato F lix party mix 60 g', 'snack gato F lix party mix 60 g', 'pet', '', '', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Companino Vitalive JUNIOR 2-12 MOIS', 'Aliment complet pour chatons', 'pet', 'C r ales, viandes et sous-produits animaux (dont prot ines de poulet d syhdrat es 4% dans les croquettes au poulet), sous-produits d''origine v g tale, huiles et graisses, substances min rales, lait et produits de laiterie (1% de poudre de lait quivalent 16% de lait dans les croquettes au lait), l gumes (1% de carottes d shydrat es quivalent 8% de carottes dans les croquettes au carottes), extrait de prot ines v g tales. 62% de croquettes en forme d'' toile marron au poulet 22% de croquettes en fo', 'C r ales', '', 0, 'Carrefour', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Picnic Festival', 'Picnic Festival', 'pet', '', '', '', 0, 'Fido', 'openpetfoodfacts', 'unisex', 'cat');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Friandises Pour Chien Adulte Medium +10kg Hygi ne Bucco Dentaire DENTALIFE', 'DENTALIFE', 'pet', 'C reales, Glyc rol, Substances min rales, Levures, Huiles et graisses, Viandes et sous-produits animaux 1.1%, Equivalent 4% de viandes et sous-produits animaux r hydrat s', 'C reales', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat'),
  ('p t pour chat junior au saumon', 'p t pour chat junior au saumon', 'pet', 'Viandes et sous-produits animaux, Extraits de prot ines v g tales, substances min rales, L gumes (0,6% de carottes s ch es, quivalent 5,4% de carottes), sucres', 'Viandes et sous-produits animaux', '', 0, 'purina', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Knabber Snack Lachs', 'Knabber Snack Lachs', 'pet', '', '', '', 0, 'Coshida', 'openpetfoodfacts', 'unisex', 'pet'),
  ('croquette adulte light/st rilis moyenne et grande race', 'Croquette pour chien st rilis', 'pet', 'Bl , Ma s, viandes d shydrat es de canard 16%, graisse de canard, pulpe de betterave, gluten de ma s, poudre d''oeuf, levures, hydrolysat de prot ines animales, argile, chlorure de sodium, glucosamine, sulfate de chondro tine. Additifs nutritionnels au kg: E672 / Vitamine A: 20000 UI, E671 / Vitamine D3: 2000 UI, Vitamine E: 400 mg E2/Iode : 2mg E6/Zinc: 200mg E4/Cuivre: 23mg E8/S l nium: 0.4mg E5/mangan se: 68mg Conservateurs: Liants E562: S piolite 18730mg/Kg E558: Montmorillonite 3700mg/Kg Ene', 'Bl', '', 0, 'octave prestige', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Gold Mousseline Gourmet', 'P te pour chat', 'pet', 'Viandes et sous-produits animaux (dont b uf 4%), sous-produits d''origine v g tale, substances min rales, sucres. Additifs: Additifs nutritionnels: UV/kg: Vit A: 1440; Vit D : 220; mg/kg: Fe(E1): 10; (E2): 0,2; Cu(E4): 0,9; Mn(E5): 1,9; Zn(E6): 10. Additifs technologiques: Avec conservateurs. Constituants analytiques : Humidit : 77,0%, Prot ine: 11,0%, Teneur en mati res grasses: 7,0%, Cendres brutes: 3,0%, Cellulose brute: 0,1%.', 'Viandes et sous-produits animaux (dont b uf 4%)', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Felix Soup', 'Felix Soup', 'pet', 'Viandes et sous-produits animaux (dont b uf 4%), Extraits de prot ines v g tales, Poissons et sous-produits de poissons, Substances min rales, Sucres, Sous-produits d''origine v g tale, Levures. Additifs: ar mes Samenstelling: Vlees en dierlijke bijproducten (waarvan rund 4%), Plantaardige eiwitextracten, Vis en visbijproducten, Mineralen, Suiker, Plantaardige bijproducten, Gist. Toevoegingsmiddelen: Smaakstoffen au poulet / met kip Composition: Viandes et sous-produits animaux (dont poulet 4 %),', 'Viandes et sous-produits animaux (dont b uf 4%)', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'pet'),
  ('freya', 'freya', 'pet', 'Dried chicken protein (38%), whole grain maize, whole grain wheat whole peas, chicken sh and chicken protein, dried beet pulp, salmon oil, dried chicory root (a natural source of fructo-oligosaccharides and inulin), minerals, yeast hydrolysate (a natural source of manna-oligosaccharides and beta gucans) Additives (per kg Nutritional additives: Vitamin A: 20000 IU Vitamin D3: 1750 IU; Vitamin E: 200 mg: Taurine: 1500 mg: Iron (Iron sulphate monohydrate): 70.0 mq; lodine (Calcium iodate anhydrous)', 'Dried chicken protein (38%)', '', 0, NULL, 'openpetfoodfacts', 'unisex', 'cat'),
  ('Dentalife', 'Dentalife', 'pet', 'Viandes et sous-produits animaux (20% de prot ines de volaille d shydrat es dont 4% de poulet), C r ales, Extraits de prot ines v g tales, Huiles et graisses, Sous-produits d''ange v g tale, Substances min rales, Poissons et sous-produits de poissons, Glyc rol, Levures. Additifs: Additifs nutritionnels: UV/kg: Vit A: 32000; Vit D 1000; Vit E 950 Sulfate de fer (1) monohydrat : (Fe: 100); lodate de calcium anhydre: (1: 2,5); Sulfate de cuivre (II) pentahydrat : (Cu: 15); Sulfate manganeux monohydr', 'Viandes et sous-produits animaux (20% de prot ines de volaille d shydrat es dont 4% de poulet)', '', 0, 'Purina', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Katzenfutter Fisch Coshida', 'Katzenfutter Fisch Coshida', 'pet', '', '', '', 0, 'Lidl', 'openpetfoodfacts', 'unisex', 'cat'),
  ('A la dinde et au poulet', 'A la dinde et au poulet', 'pet', '', '', '', 0, NULL, 'openpetfoodfacts', 'unisex', NULL);
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Soup', 'Soup', 'pet', 'Viande de poulet (dont filet de poulet 14%), thon certifi MSC (4%), foie de poulet, amidons de tapioca, carottes, gluten de bl , substances min rales.', 'Viande de poulet (dont filet de poulet 14%)', '', 0, 'Sheba', 'openpetfoodfacts', 'unisex', NULL),
  ('Soupe', 'Soupe', 'pet', 'filets de poulet (23%), amidon de tapioca, carottes, gluten de bl , substances min rales. Constituants analytiques (%): prot ine: 8.2; teneur en mati res grasses: 1.0; mati re inorganique: 0.03 cellulose brute: 0.75, humidit : 88.5.', 'filets de poulet (23%)', '', 0, 'sheba', 'openpetfoodfacts', 'unisex', NULL),
  ('Pat with Chicken', 'Pat with Chicken', 'pet', '', '', '', 0, 'Les Repas Plaisir', 'openpetfoodfacts', 'unisex', 'cat'),
  ('plenima', 'plenima', 'pet', 'saumon 20%, pois, prot ines animales d shydrat es, prot ines de saumon d shydrat es 10%, amidon de pomme de terre, prot ine de volaille hydrolys es, graisse de volaille, pulpe de betteraves d shydrat es 3%, graine de lin, min raux, prot ines animales hydrolys es, fibre v g tales, huile de poisson, chlorure de potassium, pommes d shydrat es, carottes d shydrat es, brocolis d shydrat es, canneberge d shydrat es.', 'saumon 20%', '', 0, 'leclerc', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Tender with Poultry', 'Tender with Poultry', 'pet', '', '', '', 0, 'Micho', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Chicken Mini Sticks', 'Chicken Mini Sticks', 'pet', '', '', '', 0, 'Trixie', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Friskies Balance', 'Friskies Balance', 'pet', '', '', '', 0, 'purina', 'openpetfoodfacts', 'unisex', NULL),
  ('Felix', 'Felix', 'pet', '', '', '', 0, NULL, 'openpetfoodfacts', 'unisex', 'pet'),
  ('Fresh carp & trout for adult cats sterilized', 'cat food for adult sterilized cats', 'pet', 'Fresh carp 25%, Dried trout 20%, Hydrolyzed salmon 14%, Dried salmon 12%, Pumpkin, Chicken fat, Chickpeas, Peas, Chicken liver 3%, Salmon oil 2%, Apples, Carrots, Flaxseed, Hydrolyzed crustacean shells, Cartilage extract, Brewer''s yeast, Chicory root, Yucca schidigera 0.01%, Algae 0.01%, Psyllium 0.01%, Thyme 0.01%, Rosemary 0.01%, Oregano 0.01%, Cranberries 0.0008%, Blueberries 0.0008%, Sea buckthorn 0.0008%, Ginger root 0.0008%, Sage 0.0008%', 'Fresh carp 25%', '', 0, 'Carnilove', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Terrine Gourmande Dinde, P tes Et L gumes', 'Terrine Gourmande Dinde, P tes Et L gumes', 'pet', '', '', '', 0, NULL, 'openpetfoodfacts', 'unisex', 'pet');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Aliment complet pour chien adultes au veau et aux des de carottes', 'Aliment complet pour chien adultes au veau et aux des de carottes', 'pet', 'Viandes et sous-produits animaux (min 55% dont veau min 4%), l gumes (carottes min 4%), substances min rales, sous produits d''origine v g tale.', 'Viandes et sous-produits animaux (min 55% dont veau min 4%)', '', 0, 'Cesar', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Friandises Les Irr sistibles saumon', 'Friandises Les Irr sistibles saumon', 'pet', 'C r ales, sous-produits d''origine v g tale, huiles et graisses, viandes et sous-produits animaux, extraits de prot ines v g tales, substances min rales.', 'C r ales', '', 0, 'Whiskas', 'openpetfoodfacts', 'unisex', 'cat'),
  ('CHAT STERILISE SAUMON', 'CHAT STERILISE SAUMON', 'pet', 'Saumon (15%), prot ines de volaille d shydrat es, bl (15%), farine de soja, ma s, gluten de ma s, gluten de bl , graisse animale, pulpe de bette d shydrat e, racine de chicor e d shydrat e, prot ines de poisson d shydrat es, sels min raux, hydrolysate (avec ajout de 0,025% de poudre de Lactobacillus Delbrueckii et Fermentum trait e thermiquement), levures. Additifs : Additifs nutritionnels : UI/kg : Vit A : 36 960 ; Vit D3 : 1 200 ; Vit E : 460 mg/kg : Vit C : 140 ; Taurine : 780 ; Sulfate ferre', 'Saumon (15%)', '', 0, 'PURINA', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Tendres effil s selection de la campagne', 'Tendres effil s selection de la campagne', 'pet', '', '', '', 0, 'Felix, Purina', 'openpetfoodfacts', 'unisex', 'cat'),
  ('Gourmet Huhn', 'Gourmet Huhn', 'pet', '', '', '', 0, 'Huhn, Purina', 'openpetfoodfacts', 'unisex', NULL),
  ('RC cat food urinary care', 'RC cat food urinary care', 'pet', 'Viandes et sous-produits animaux, c r ales, sous-produits d''origine v g tale, substances min rales, sucres. ADDITIFS (au kg): Additifs nutritionnels : Vitamine D3: 330 UI, E1 (Fer): 3 mg, E2 (lode): 0,2 mg, E4 (Cuivre): 2 mg, E5 (Mangan se): 1,9 mg, E6 (Zinc): 9 mg.', 'Viandes et sous-produits animaux', '', 0, 'Royal canin', 'openpetfoodfacts', 'unisex', 'cat'),
  ('whiskas temptations poulet fromage', 'whiskas temptations poulet fromage', 'pet', '', '', '', 0, NULL, 'openpetfoodfacts', 'unisex', 'pet'),
  ('biscottini a forma di osso', 'biscottini a forma di osso', 'pet', '', '', '', 0, 'Eurospin', 'openpetfoodfacts', 'unisex', 'pet'),
  ('Appetito Difficile', 'Appetito Difficile', 'pet', '', '', '', 0, 'affinity', 'openpetfoodfacts', 'unisex', 'cat');
