-- baby: 75 rows

INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Lait pour nourrissons', 'Lait pour nourrissons', 'baby', '', '', '', 0, 'Bl dina', 'openfoodfacts', 'unisex', 'baby'),
  ('GUIGOZ 3 BIO Croissance 800g', 'Lait de suite pour nourrissons   partir de 10 mois et aliment lact  en poudre pour enfants en bas  ge', 'baby', 'skimmed milk*, maltodextrin*, vegetable oils* (sunflower rich in oleic acid*, rapeseed*, sunflower*), lactose*, minerals (calcium, sodium, potassium and magnesium citrates, potassium phopshate , potassium chloride, ferrous sulphates, zinc, copper and manganese sulphates, potassium iodide, sodium selenate), vitamins (a, b1, b3, b5, b6, b8, b9, b12, c, d,  e, k), emulsifier (soy lecithin*), oil extr', 'skimmed milk*', '', 0, 'Nestl , Guigoz', 'openfoodfacts', 'unisex', 'baby'),
  ('Lait infantile 0-6 mois', 'Lait infantile 0-6 mois', 'baby', '', '', '', 0, 'Les petits culottes', 'openfoodfacts', 'unisex', 'baby'),
  ('Nursie', 'Nursie', 'baby', '', '', '', 0, 'Danone', 'openfoodfacts', 'unisex', 'baby'),
  ('Cerelac', 'Cerelac', 'baby', 'Wheat flour, skimmed milk, sucrose, palm olein, banana, orange, acidity regulator: disodium phosphate, calcium carbonate, apple, vitamins, ferrous fumarate, vanillin, zinc sulphate, apple flavor, potassium iodide. Allergens: contains Gluten and Milk. May contain Soya', 'Wheat flour', '', 0, 'Nestl', 'openfoodfacts', 'unisex', 'baby'),
  ('Similac Advance', 'Similac Advance', 'baby', 'NONFAT MILK, LACTOSE, HIGH OLEIC SAFFLOWER OIL, WHEY PROTEIN CONCENTRATE, SOY OL COCONUT OL, GALACTOOLIGOSACCHARIDES; LESS THAN 2% OF: C. COHNI OL, M. ALPINA OL, BETA - W CARUTENE, LUTEN, LYCOPENE, POTASSIUM CITRATE, CALCIUM CARBONATE, ASCORBIC ACID, SOY LECTHIN, PUIASSUM CALORIDE, MAGNESIUM CHLORIDE, FERROUS SULFATE, CHOLINE BITARTRATE, CHOLNE CHLORDE, ASCORBYL PALMITATE, SALT, TAURINE, INOSITOL,', 'NONFAT MILK', '', 0, 'Abbott', 'openfoodfacts', 'unisex', 'baby'),
  ('Liptomil  Plus Infant Milk Formula 1', 'Liptomil  Plus Infant Milk Formula 1', 'baby', 'Skimmed milk, lactose, vegetable oils and fats (palm oil, coconut fat, rapeseed oil, sunflower oil), whey protein concentrate, galactooligosaccharide syrup (GOS), minerals (potassium citrate, calcium phosphate, sodium citrate, calcium chloride, calcium citrate, magnesium chloride, iron (II) gluconate, zinc sulphate, copper sulphate, manganese sulphate, potassium iodate, sodium selenate) emulsifier', 'Skimmed milk', '', 0, 'Liptomil Plus', 'openfoodfacts', 'unisex', 'baby'),
  ('Follow on milk', 'Follow on milk', 'baby', 'Dairy-based blend (of which 29% is fermented) [Lactose (from milk), Vegetable oils (High oleic sunflower oil, Coconut oil, Rapeseed oil, Sunflower oil), Skimmed milk, Demineralised whey (from milk), Whey concentrate (from milk), Calcium phosphate, Fish oil, Potassium chloride, Potassium citrate, Choline chloride, Sodium citrate, Vitamin C, Calcium carbonate, Emulsifier (Soy lecithin), Inositol, Ma', 'Dairy-based blend (of which 29% is fermented) [Lactose (from milk)', '', 0, 'Aptamil', 'openfoodfacts', 'unisex', 'baby'),
  ('Lait de suite', 'Lait de suite', 'baby', 'Lait  cr m , maltodextrines, lactose (lait), huiles v g tales (palme, sola calcium, phosphate tricalcique, vitamines (A, B1, B12, B2, B6, C, D, E, K, coprah), carbonate de calcium,  mulsifiant (l cithine de soja), chlorure de acide folique, acide pantoth nique, biotine, niacine), chlorure de sodium, bitartrate de choline, sulfate de fer, citrate tripotassique, L-tryptophane oxyde de magn sium, sul', 'Lait  cr m', '', 0, 'Novalac', 'openfoodfacts', 'unisex', 'baby'),
  ('Lait Croissance 3', 'Lait Croissance 3', 'baby', 'Lait partiellement  cr m , eau, lactose, huiles de colza et de tournesol (dont antioxydant : extraits riches en tocoph rols), maltodextrine de ma s, ar me naturel de vanille,  mulsifiant : mono - et diglyc rides d''acides gras, min raux (glyc rophosphate et gluconate de calcium, citrate de sodium, sulfate de fer, sulfate de zinc, sulfate de cuivre, iodure de potassium, carbonate et hydroxyde de pot', 'Lait partiellement  cr m', '', 0, 'Milsani', 'openfoodfacts', 'unisex', 'baby');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('1 First Baby Milk Formula From Birth', '1 First Baby Milk Formula From Birth', 'baby', '*Suitable as a sole source of nutrition from birth and as part of a weaning diet from t months. As required by the legislation for all infant formula. NAREDIENTS: Water, Dairy-based blend (of which 26% is fermented) (Skimmed milk Lactose (from milk), Vegetable oils (High oleic sunflower oil, Coconut oil, Rapeseed o Sunflower oil), Demineralised whey (from milk), Emulsifier (Soy lecithin), Whey con', '*Suitable as a sole source of nutrition from birth and as part of a weaning diet from t months. As required by the legislation for all infant formula. NAREDIENTS: Water', '', 0, '', 'openfoodfacts', 'unisex', 'baby'),
  ('Gentlease Infant Formula', 'Gentlease Infant Formula', 'baby', 'Corn Syrup Solids, Partially Hydrolyzed Nonfat Milk Solids, Whey Protein Concentrate Solids (Soy), Vegetable Oil (Palm Olein Oil, Soy Oil, Coconut Oil, High Oleic Sunflower Oil), Mortierella Alpina Oil, Schizochytrium Sp. Oil, Vitamin A Palmitate, Vitamin D3, Vitamin E Acetate, Vitamin K1, Thiamin Hydrochloride, Riboflavin, Vitamin B6 Hydrochloride, Vitamin B12, Niacinamide, Folic Acid, Calcium Pa', 'Corn Syrup Solids', '', 0, 'Enfamil, Mead Johnson', 'openfoodfacts', 'unisex', 'baby'),
  ('Go & Grow by Similac Advanced Formula', 'Go & Grow by Similac Advanced Formula', 'baby', 'Skim milk, Dry skim milk, Sugars (Lactose), High oleic sunflower oil, Soy oil, Coconut oil, Short-chain fructooligosaccharides (scFOS), 2''-fucosyllactose (2''-FL), Soy lecithin, Schizochytrium sp. oil (a source of DHA), Potassium hydroxide, Ascorbyl palmitate, Mixed toco - pherols, Cytidine 5''-monophosphate, Disodium uridine 5''-monophosphate, Lutein, Adenosine 5''-monophosphate, Disodium guanosine 5', 'Skim milk', '', 0, 'Abbott', 'openfoodfacts', 'unisex', 'baby'),
  ('Breast milk substitute', 'Breast milk substitute', 'baby', 'Water, skimmed milk, lactose (milk), vegetable oils (sunflower, rapeseed), whey protein (milk), long chain polyunsaturated fatty acids (DHA (fish), AA (Mortierella alpina oil)),calcium citrate 2''-Fucosyllactose (2''FL), emulsifier (soya lecithin), potassium citrate, choline bitartrate, potassium chloride, magnesium chloride, L-phenylalanine, sodium chloride, vitamin C, calcium phosphate, taurine, i', 'Water', '', 0, 'Sma pro', 'openfoodfacts', 'unisex', 'baby'),
  ('Gentle Nutrition Infant Formula 0-6 Months', 'Gentle Nutrition Infant Formula 0-6 Months', 'baby', 'milk solids, vegetable oils (contains soy, antioxidant (ascorbyl palmitate, citric acid)), maltodextrin, galacto-oligosaccharides (contains milk), dried omega lcpufas (contain fish, milk, soy, antioxidant (mixed tocopherols, dl-alpha tocopherol, ascorbyl palmitate, sodium ascorbate, citric acid)), long chain polyfructose, emulsifier (soy lecithin), taurine, choline chloride, l-carnitine, inositol', 'milk solids', '', 0, 'Karicare', 'openfoodfacts', 'unisex', 'baby'),
  ('MTR DOSA', 'MTR DOSA', 'baby', 'Batters (Dry mix) (IFC: 6.6) : Rice flour (46%), Black gram flour (27%), Refined wheat flour (Maida), Interesterified vegetable oil, salt, Raising agent [INS 500 (ii)], Acidity regulator (INS 296), Fenugreek powder.', 'Batters (Dry mix) (IFC: 6.6) : Rice flour (46%)', '', 0, 'MTR', 'openfoodfacts', 'unisex', 'baby'),
  ('Aptamil 3 Ready To Drink Toddler Milk', 'Aptamil 3 Ready To Drink Toddler Milk', 'baby', ')))) ***1 TODDLER MILK INGKEWICHTS Skimmed milk, Water, Galacto-oligosacchari - des (GOS) (from milk), Lactose (from milk), *** Vegetable oils (Rape - seed oil, High oleic sunflower oil, Sun - flower oil), Emul - sifier (Mono - and diglycerides of fatty acids), Fructo-oligo - saccharides (FOS), Fish oil, Calcium citrate, Calcium phosphate, Calcium hydroxide, Acidity regulator (citric acid), Vitami', ')))) ***1 TODDLER MILK INGKEWICHTS Skimmed milk', '', 0, 'Aptamil', 'openfoodfacts', 'unisex', 'baby'),
  ('GUIGOZ OPTIPRO Lait Infantile 900g 1er  ge d s la Naissance', 'Lait pour nourrissons en poudre de la naissance jusqu''  6 mois', 'baby', 'LAIT  cr m , LACTOSE, LACTOSERUM doux d min ralis , huiles v g tales (tournesol riche en acide ol ique, colza, tournesol), min raux (citrates de calcium, de potassium et de sodium ; chlorures de magn sium, de potassium et de sodium ; phosphate de sodium ; sulfates ferreux, de zinc, de cuivre et de mangan se ; iodure de potassium ; s l nate de sodium), 2''-fucosyllactose, huile de POISSON,  mulsifia', 'LAIT  cr m', '', 0, 'Nestl , Guigoz, Guigoz 1, Laboratoires Guigoz', 'openfoodfacts', 'unisex', 'baby'),
  ('Gate 2 Follow On Baby Milk Formula', 'Gate 2 Follow On Baby Milk Formula', 'baby', '', '', '', 0, '', 'openfoodfacts', 'unisex', 'baby'),
  ('Kendamil Organic', 'Kendamil Organic', 'baby', 'Organic whole milk, Organic demineralised milk whey protein powder, Organic skimmed milk, Organic vegetable Oils (sunflower, coconut, rapeseed), Organic Galacto-oligosaccharide (from milk), Calcium citrate, Sodium citrate, Potassium chloride, Calcium lactate, Magnesium chloride, Docosahexaenoic Acid, Vitamin C, Potassium hydroxide, Choline bitartrate, Inositol, Iron pyrophosphate, Zinc sulphate, V', 'Organic whole milk', '', 0, 'Kendamil', 'openfoodfacts', 'unisex', 'baby');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Infant Formula', 'Infant Formula', 'baby', 'nonfat milk, lactose, vegetable oil, palm oil, coconut oil, soy oil, high oleic sunflower oil, whey protein concentrate, less than 2% galactooligosaccharides, polydextrose, mortierella alpina oil, schizochytrium sp. oil, calcium carbonate, calcium phosphate, potassium citrate, ferrous sulfate, potassium chloride, magnesium oxide, sodium chloride, ascorbyl palmitate, mixed tocopherols, zinc sulfate', 'nonfat milk', '', 0, 'Enfamil', 'openfoodfacts', 'unisex', 'baby'),
  ('Aptamil Gold Stage 3 Follow-up Formula Powder (From 12 Months Onwards)', 'Aptamil Gold Stage 3 Follow-up Formula Powder (From 12 Months Onwards)', 'baby', 'Milk Solids, Demineralized Whey and Whey Solids, Edible Vegetable Oils (Corn Oil and Canola Oil), Minerals*, Docosahexaenoic Acid Powder-0.76% (Schizochytrium sp.oil), Arachidonic Acid Powder-0.64% (Mortierella Alpina Oil), Choline, Emulsifier (Soy Lecithin), Acidity Regulator (Sodium Hydroxide), Nucleotides Premix-0.027%, Vitamins*, Antioxidant (Mixed Tocopherols),Taurine, L-Carnitine, Inositol,', 'Milk Solids', '', 0, 'Aptamil', 'openfoodfacts', 'unisex', 'baby'),
  ('Similac Pro-Advance Step 1', 'Similac Pro-Advance Step 1', 'baby', 'Lactose, Dry or evaporated skim milk, High oleic safflower oil, Whey protein concentrate, Soy oil, Coconut oil, Fructooligosaccharides, Whey protein hydrolysate, M. alpina oil (a source of ARA), 2''-fucosyllactose (2''-FL), Schizochytrium sp. oil (a source of DHA), Soy lecithin, L-tryptophan, Taurine, M-inositol, Cytidine 5''-monophosphate, Ascorbyl palmitate, Disodium guanosine 5''-monophosphate, Dis', 'Lactose', '', 0, 'Similac', 'openfoodfacts', 'unisex', 'baby'),
  ('Similac', 'Similac', 'baby', '', '', '', 0, 'Abbott', 'openfoodfacts', 'unisex', 'baby'),
  ('GUIGOZ Optipro 1 500ml', 'Lait pour nourrissons liquide d s la naissance jusqu''  6 mois', 'baby', 'Eau, LAIT  cr m , LACTOSE, huiles v g tales (tournesol riche en acide ol ique, colza, tournesol), LACTOSERUM doux d min ralis , min raux (citrates de calcium et de potassium ; chlorures de potassium, de magn sium et de sodium ; phosphate de calcium, sulfates ferreux, de zinc, de cuivre et de mangan se ; iodure de potassium, s l nate de sodium),  mulsifiant (l cithine de SOJA), m lange 2''-Fucosylla', 'Eau', '', 0, 'Nestl , Guigoz', 'openfoodfacts', 'unisex', 'baby'),
  ('PICOT ACTION TRANSIT LAIT 1ER AGE', 'PICOT ACTION TRANSIT LAIT 1ER AGE', 'baby', 'INFORMATIONS NUTRITIONNELLES Ou NOURRISSON DE MOINS DE 6 MOIS, EN CAS DE RALENTI. Ingr dients du produit recons  i  : lactos rum d min plis  soja, coprah), lait  cr m , lactose (lait), min raux (chlorure de phosphate de magn sium, chlorure de sodium, hydroxyde de de sodium, iodure de potassium, sulfate de cuivrer sulfate (pal%taoline, (C, E, PB B5, A, K, BI, B6, D, B9, H, B12), taurine, antioxydan', 'INFORMATIONS NUTRITIONNELLES Ou NOURRISSON DE MOINS DE 6 MOIS', '', 0, 'Picot', 'openfoodfacts', 'unisex', 'baby'),
  ('Lait infantile Evolia relais 1', 'Lait pour nourrissons en poudre de la naissance jusqu''  6 mois', 'baby', 'Lait_  cr m , _lactose_, huiles v g tales (ol ine de palme, ol ine de colza, ol ine de coprah, ol ine de tournesol), prot ines de solubles de _lait_, galacto-oligosaccharides 3%, citrates de potassium, citrates de calcium, citrates de sodium,  mulsifiant : l cithine de _soja_; chlorure de magn sium et chlorure de sodium, maltodextrine, fructo-oligosaccharides 0,16%, huile de _poisson_, L-ph nylala', 'Lait_  cr m', '', 0, 'Guigoz', 'openfoodfacts', 'unisex', 'baby'),
  ('Lait b b  1er Age Guigoz', 'Lait b b  1er Age Guigoz', 'baby', '', '', '', 0, 'Guigoz', 'openfoodfacts', 'unisex', 'baby'),
  ('BABY ADVANCE 2 - 400 gr', 'Infant Formula Stage 2', 'baby', '', '', '', 0, 'PRONUBEN', 'openfoodfacts', 'unisex', 'baby'),
  ('Nursie Lactofidus', 'Nursie Lactofidus', 'baby', 'Lait  cr m  - Maltodextrines - Huiles v g tales (palme, coprah, colz , tournesol). proteines de lactos rum (lait) -  mulsifiant : l cithine de soja - Taurine - Citrate de choline - Inosit l - Min raux: hydroxyde de calcium, chlorure de magn sium, citrates de sodium et de potassium, sulfates de fer, de zinc, de cuivre et de mangan se, iodure de potassium-Vitamines: A, D, E, K, C, B1, B2, B3, B6, ac', 'Lait  cr m  - Maltodextrines - Huiles v g tales (palme', '', 0, 'bl dina', 'openfoodfacts', 'unisex', 'baby');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Organic infant formula milk-based powder with iron', 'Organic infant formula milk-based powder with iron', 'baby', 'organic nonfat milk, organic expeller pressed vegetable oils (palm or palm olein, _soybean_, coconut and high oleic safflower seed or sunflower seed), organic corn syrup solids, organic maltodextrin (derived from corn, rice or potato), contains less than 1% of each of the vitamin a palmitate,beta-carotene, cholecalciferol (vitamin d3), dl-alpha tocopheryl acetate (vitamin e), mixed tocopherol conc', 'organic nonfat milk', '', 0, '365 everyday value', 'openfoodfacts', 'unisex', 'baby'),
  ('Organic  Infant Powder Formula with Iron', 'Organic  Infant Powder Formula with Iron', 'baby', 'Organic Lactose, Organic Nonfat Milk, Organic Oils (Organic Palm or Palm Olein, Organic Soy, Organic Coconut, Organic High Oleic Safflower or Sunflower Oil), Organic Whey Protein Concentrate, Less Than 1: Mortierella Alpina Oil*, Crypthecodinium Cohnii Oil**, Fructooligosaccharide, Lutein, L-Carnitine, Vitamin A Palmitate, Beta-Carotene, Vitamin D (Cholecalciferol), Vitamin E (DL-Alpha Tocopheryl', 'Organic Lactose', '', 0, 'Earth''s Best', 'openfoodfacts', 'unisex', 'baby'),
  ('Lactel eveil croissance Nature', 'Lactel eveil croissance Nature', 'baby', 'AUMENT LACT  LIQUIDE DESTIN  AUX ENFANTS EN BAS ACE DE 1  3 ANS STERIISE UNT. ngr dients : Lait  cr m , lactos rum concentr  d min ralis  partiellement eydrat  (lait), eau, cr me (lait), maltodextrines, huiles v g tales (colza, bumesol), min raux (lait) (citrate de calcium, citrate de potassium, citrate de odum, phosphate de potassium, gluconate de zinc, sulfate fereux, sel nite de Mdun, lodure de', 'AUMENT LACT  LIQUIDE DESTIN  AUX ENFANTS EN BAS ACE DE 1  3 ANS STERIISE UNT. ngr dients : Lait  cr m', '', 0, 'Lactel', 'openfoodfacts', 'unisex', 'baby'),
  ('NAN ET2', 'NAN ET2', 'baby', 'Prote na de suero de leche de vaca desmineralizado, aceites vegetales, leche descremada de vaca, maltodextrina, lactosa, contrato de calcio, leg tima de soya,fosfato dibasico de sodio, hmo, aceite de pescado,fosfato dibasico de potasio, vitamina c, cloruro de potasio, cloruro de magnesio, cloruro de sodio, sulfato ferroso sulfato de zinc, fosfato dibasico de calcio, vitamina e, cultivos de lactoba', 'Prote na de suero de leche de vaca desmineralizado', '', 0, 'Nestl', 'openfoodfacts', 'unisex', 'baby'),
  ('Kavza Energie', 'Kavza Energie', 'baby', '', '', '', 0, 'Kavza Energie', 'openfoodfacts', 'unisex', 'baby'),
  ('PRO-AVANCE Infant Formula', 'Infant Formula', 'baby', 'Nonfat Milk, Lactose, Whey Protein Concentrate, High Oleic Safflower Oil, Soy Oil, Coconut Oil. Less than 2% of: C. Cohnii Oil, M. Alpina Oil, 2''-Fucosyllactose, Fructooligosaccharides, Beta-Carotene, Lutein, Lycopene, Potassium Citrate, Calcium Carbonate, Ascorbic Acid, Soy Lecithin, Potassium Chloride, Magnesium Chloride, Ferrous Sulfate, Choline Bitartrate, Choline Chloride, Ascorbyl Palmitate,', 'Nonfat Milk', '', 0, 'Abbott', 'openfoodfacts', 'unisex', 'baby'),
  ('Sous Video Schweine Filet', 'Sous Video Schweine Filet', 'baby', 'Schweinefiletzubereitung 77 % (Schweinefilet 89 %, Wasser 9 %, Speisesalz, Stabilisator Natriumcitrate, S ureregulator Natriumcarbonate, getrockneter Glukosesirup, Antioxidationsmittel Natriumascorbat, Gew rzextrakte, Raps l), Sauce 23 % (Wasser, Sahne 17 %, Milcheiwei , modifizierte St rke, getrockneter Glukose - sirup, Lactose, Sonnenblumen l, Zucker, Speisesalz, Gew rze, Karamell, Weinbrand, na', 'Schweinefiletzubereitung 77 % (Schweinefilet 89 %', '', 0, 'Bille', 'openfoodfacts', 'unisex', 'baby'),
  ('Advantage infant formula milk based powder with iron', 'Advantage infant formula milk based powder with iron', 'baby', 'nonfat milk, lactose, palm olein, whey protein concentrate, soy oil, coconut oil, high oleic (safflower or sunflower) oil, fructooligosaccharide (fos), less than 1%: crypthecodinium cohnii oil*, mortierella alpina oil , 2''-fucosyllactose (2''-fl),how many, beta-carotene, lutein, potassium bicarbonate, calcium carbonate, ascorbic acid, soy l cithin, monoglycerides, calcium chloride, calcium hydroxid', 'nonfat milk', '', 0, 'Aldi', 'openfoodfacts', 'unisex', 'baby'),
  ('Lait pour nourissons', 'Lait pour nourissons', 'baby', 'Lait  cr m *, petit lait* en poudre, huiles v g tales* (huile de palme*, huile de colza*, huile de tournesol*), lactose*, huile de poisson'', chlorure de calcium. citrate de potassium, huile Mortierella alpina, choline, citrate de sodium, L-tyro - sine, L-ph nylalanine, carbonate de calcium, L-tryptophane, sulfate de zinc, sulfate ferreux, acide lactique stabilisant, vitamine C, niacine, vitamine E', 'Lait  cr m *', '', 0, 'Hipp', 'openfoodfacts', 'unisex', 'baby'),
  ('Happy Baby Organic Sensitive Infant Formula', 'Happy Baby Organic Sensitive Infant Formula', 'baby', 'ORGANIC NONFAT MILK, ORGANIC MALTODEXTRIN, ORGANIC GLUCOSE SYRUP SOLIDS, ORGANIC PALM OLEIN OR PALM OIL, ORGANIC SOY OIL, ORGANIC COCONUT OIL, ORGANIC HIGH OLEIC (SAFFLOWER OR SUNFLOWER) OIL ORGANIC GALACTOOLIGOSACCHARIDES (GOS), ORGANIC WHEY PROTEIN CONCENTRATE, LESS THAN 1% FRUCTOOLIGOSACCHARIDE (FOS), CHOLINE BITARTRATE, POTASSIUM CHLORIDE, ORGANIC SOY LECITHIN, CALCIUM HYDROXIDE, MORTIERELLA A', 'ORGANIC NONFAT MILK', '', 0, 'Happybaby', 'openfoodfacts', 'unisex', 'baby');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Infant Formula Stage 1', 'Infant Formula Stage 1', 'baby', '12:02 myorganicformula.com lactose - your baby''s essential carbohydrate source. N LTE Ty   Proteins. Nannycare contains nutritionally complete, full-cream goat''s milk, with a mix of curds and whey protein that mimics breast milk.   Fats. Nannycare contains a blend of vegetable oils and essential healthy fats, including omega 3 and 6 and DHA. i Offcam acara Pasteurised Goat Milk Solids, Lactose (Fr', '12:02 myorganicformula.com lactose - your baby''s essential carbohydrate source. N LTE Ty   Proteins. Nannycare contains nutritionally complete', '', 0, 'Namnycare', 'openfoodfacts', 'unisex', 'baby'),
  ('Walnuss salziges Karamell', 'Walnuss salziges Karamell', 'baby', 'SAHNE, Zucker, Dextrose, Wasser, MAGER - MILCHPULER, VOLLMILCHPULVER, MILCHEIWEISS, Maltodextrin, Emulgatoren: E471, E472a, E473, E477, Verdickungsmittel: E410, E401, Aromen, SAHNE - PULVER, MOLKE, S urungsmittel: Zitronens ure, pulveri - sierter MAGERJOGHURT, WALNUSSMARK, Pflanzen l (Sonnenblume), MOLKENPULVER, karamelisierter Zucker, Fleur de Sel, fettarmes Kakaopulyer, Waln sse, Emulgator Sojal', 'SAHNE', '', 0, 'Elvis', 'openfoodfacts', 'unisex', 'baby'),
  ('Infant Formula for Babies Sensitive to Lactose', 'Infant Formula for Babies Sensitive to Lactose', 'baby', '', '', '', 0, 'Kirkland', 'openfoodfacts', 'unisex', 'baby'),
  ('Pediasure Vanilla', 'Pediasure Vanilla', 'baby', 'Concentrated Corn Syrup, Sucrose, Vegetable Oil (Soybean Oil, High Oleic Sunflower Oil, MCT Oil), Milk Protein Concentrate (11.3%), Whey Protein Concentrate (2.6%), 15 MINERALS (Sodium Chloride,Iron Sulfate, Zinc Sulfate, Manganese Sulfate, Copper Sulfate, Potassium Iodide, Chromium Chloride, Sodium Selenite, Sodium Molybdate), Oligofructose, Soy Protein Isolate (2.3%), Synthetic Flavor, 16 VITAMI', 'Concentrated Corn Syrup', '', 0, 'Pediasure', 'openfoodfacts', 'unisex', 'baby'),
  ('Pronuben baby advance 2', 'Follow on baby formula 6-12 months', 'baby', '', '', '', 0, 'PRONUBEN, Pronuben baby', 'openfoodfacts', 'unisex', 'baby'),
  ('Pronuben baby advance 1', 'Infant formula 0-6 months', 'baby', '', '', '', 0, 'Pronuben baby', 'openfoodfacts', 'unisex', 'baby'),
  ('Pronuben baby advance 3', 'Growing up formula 1-3 years', 'baby', '', '', '', 0, 'Pronuben baby', 'openfoodfacts', 'unisex', 'baby'),
  ('Zwieback', 'Zwieback', 'baby', 'odzone (jaja*.cukier) du bamista 90%, gluten pszenny, m ka ze s odu j czmiennego, m ka zes odu pszennego mauren 2,7g, Kohlenhydrate 59,6g, davon Zucker 8,9g, Eiwei  16,4g, Salz0,73g. am verarbeitet. *Eier aus Freilandhaltung. Vor W rme sch tzen und trocken lagem &lt;ST B St cke. N hrwertdeklaration pro 100g: Energie 1633 kJ/387 kcal, Fett7,6g, avongesinit doprzetwarzania maki: kwas askorbinowy), s', 'odzone (jaja*.cukier) du bamista 90%', '', 0, 'Continental Bakery', 'openfoodfacts', 'unisex', 'baby'),
  ('Earths best', 'Earths best', 'baby', 'Organic glucose syrup solids, organic palm oil or palm oil organic way protein concentrate organic milk, protein concentrate organic soy oil, organic coconut oil, organic high oil, flour or sunflower oil less than one percent Montreal Alpine oil SCHIZOCWYTRIUMSP oil FOST McCaine, vitamin A Paul Beta carotene vitamin D vitamin K mix talk barrel concentrate vitamin E acro palate diamine hydrochlorid', 'Organic glucose syrup solids', '', 0, 'Earths best', 'openfoodfacts', 'unisex', 'baby'),
  ('Pronuben baby lactose free', 'Lactose free formula from birth', 'baby', 'Maltodextrin, Vegetable oils (palm, palm-kernel, rapeseed, sunflower, high oleic sunflower), Whey protein concentrate, calcium caseinate, Minerals (Monocalcium phosphate, Potassium chloride, Trisodium citrate, Calcium hydroxide, Disodium phosphate, Magnesium sulfate, Potassium citrate , Potassium hydroxide, Ferrous sulfate, Chromium chloride, Zinc sulfate, Sodium molybdate, Copper sulfate, Mangane', 'Maltodextrin', '', 0, 'Pronuben baby', 'openfoodfacts', 'unisex', 'baby');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Spargelstangen', 'Spargelstangen', 'baby', '', '', '', 0, 'Freshona', 'openfoodfacts', 'unisex', 'baby'),
  ('360 Total Care Infant Formula', '360 Total Care Infant Formula', 'baby', 'WATER, NONFAT MILK, LACTOSE, HIGH OLEIC SAFFLOWER OIL, SOY OIL, COCONUT OIL, WHEY PROTEIN CONCENTRATE, HUMAN MILK OLIGOSACCHARIDES (2''-FUCOSYLLACTOSE, LACTO-N-TETRAOSE, 3-FUCOSYLLACTOSE 6''-SIALYLLACTOSE, 3''-SIALYLLACTOSE), SCHIZOCHYTRIUM SP. OILS,M. ALPINA OIL, BETA-CAROTENE, LUTEIN, ASCORBIC ACID, CALCIUM CARBONATE, POTASSIUM CITRATE, SOY LECITHIN, MONOGLYCERIDES, POTASSIUM CHLORIDE, CARRAGEENAN,', 'WATER', '', 0, 'Abbot, Similac', 'openfoodfacts', 'unisex', 'baby'),
  ('Nurtamigen LGG 1', 'Nurtamigen LGG 1', 'baby', '', '', '', 0, 'Mead Johnson', 'openfoodfacts', 'unisex', 'baby'),
  ('First infant milk', 'First infant milk', 'baby', 'Lactose (from milk), Vegetable oils (High oleic sunflower oil, Coconut oil, Rapeseed oil, Sunflower oil), Skimmed milk, Demineralised whey (from milk), Whey concentrate (from milk), Galacto-oligosaccharides (GOS) (from milk), Cow''s milk protein, Fish oil, Calcium phosphate, Fructo-oligosaccharides (FOS), Potassium chloride, Oil from Mortierella Alpina, Sodium citrate, Choline chloride, Magnesium h', 'Lactose (from milk)', '', 0, 'Cow and Gate', 'openfoodfacts', 'unisex', 'baby'),
  ('else. Toddler Plant-Based Nutritional Supplement', 'Plant-Based Complete & Balaced Nutritional Supplement', 'baby', 'Organic Buckwheat Flour, Almond Butter, Almond Protein Powder, Tapioca Maltodextrin, Organic Rapeseed Oil. Less than 2%: Cane Sugar, Vanilla Flavour, Calcium Carbonate, Tricalcium Phosphate, Potassium Chloride, Sodium Citrate, Choline Bitartrate, Chromium Chloride, Copper Sulfate, Potassium Iodide, Ferrous Sulfate, Sodium Molybdate, Sodium Selenite, Zinc Citrate, Manganese Sulfate, Vitamin A Palmi', 'Organic Buckwheat Flour', '', 0, 'Else Nutrition', 'openfoodfacts', 'unisex', 'baby'),
  ('Organic Premium Infant Formula with Iron', 'Organic Premium Infant Formula with Iron', 'baby', 'Organic Lactose, Organic Nonfat Milk, Organic High Oleic Oil (Organic High Oleic Sunflower and/or Organic High Oleic Safflower Oils), Organic Soybean Organic Soy Lecithin, Calcium Carbonate, Calcium Phosphate, Sodium Chloride, Potassium Chloride, Potassium Citrate, Magnesium Phosphate, Choline Bitartrate, Calcium Ascorbate, Inositol, Ferrous Sulfate, d-Alpha Tocopheryl Acetate, Zinc Sulfate, Niaci', 'Organic Lactose', '', 0, '', 'openfoodfacts', 'unisex', 'baby'),
  ('Milupa Milumil Anfangsmilch Pre 800g', 'S uglingsmilchnahrung', 'baby', 'Laktose (aus MILCH), pflanzliche  le (Sonnenblumen-, Kokosnuss-, Raps l) (24%), MAGERMILCH, demineralisierte Molke (aus MILCH), Molkenkonzentrat (aus MILCH), Galactooligosaccharide (aus MILCH), Molkenprotein (aus MILCH), FISCH L, Calciumorthophosphat, Fructooligosaccharide, Kaliumchlorid,  l aus Mortierella alpina, Natriumcitrat, Cholinchlorid, Magnesiumorthophosphat, Kaliumcitrat, Vitamin C, Inos', 'Laktose (aus MILCH)', '', 0, 'Milupa', 'openfoodfacts', 'unisex', 'baby'),
  ('Folge milch', 'Folge milch', 'baby', '', '', '', 0, 'dmBio', 'openfoodfacts', 'unisex', 'baby'),
  ('Lactogen 1', 'Baby Milk Powders', 'baby', 'Milk Solids (62.1%), Demineralised whey(21.1%), soybean oil, minerals, low erucic rapeseed oil, coconut oil, high oleic sunflower oil, sunflower oil, emulsifier (soya lecithin), vitamin, probiotic, taurine, acidity regulator, l-carnitine, chlorine bitartrate', 'Milk Solids (62.1%)', '', 0, 'Nestl', 'openfoodfacts', 'unisex', 'baby'),
  ('nan pro formula milk nestle', 'nan pro formula milk nestle', 'baby', 'Milk solids, Demineralised whey (24.1%), Soyabean oil, Minerals, Low erucic rapeseed oil, High oleic sunflower oil, Coconut oil, Sunflower oil, Emulsifier (Soya lecithin), Arachidonic acid (ARA) from Mortierella alpina oil, Docosahexaenoic acid (DHA) from Schizochytrium sp. oil, Vitamins, Probiotic (Limosilactobacillus reuteri (DSM 17938)), Taurine, Acidity regulators (Citric acid and Potassium hy', 'Milk solids', '', 0, 'Nestl', 'openfoodfacts', 'unisex', 'baby');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Similac Plus', 'Similac Plus', 'baby', 'Lactose, nonfat dry milk, edible vegetable oils (coconut oil, high oleic sunflower oil, medium chain triglycerides oil, low erucic rapeseed oil, soy oil), corn syrup solids, whey protein concentrate, fructo-oligosaccharides (FOS) (1.6%), MINERALS, arachidonic acid (AA) from M. alpina oil, emulsifier (soy lecithin), 2''-fucosyllactose (2 -FL) (human milk oligosaccharide) (0.17%), choline bitartrate,', 'Lactose', '', 0, 'Abbott', 'openfoodfacts', 'unisex', 'baby'),
  ('Kids leche fortificada', 'Kids leche fortificada', 'baby', 'Leche parcialmente descremada, fibra de ma z soluble, lecitina de soya, saborizante id ntico al natural, vitamina C, hierro, vitamina E, nicotinamida. zinc,  cido pantot nico, vitamina B6, vitamina B2. vitamina A, vitamina B1, yodo,  cido f lico, vitamina K, biotina, vitamina D y vitamina B12. Contiene leche (case na y lactosa) y soya (lecitina de soya). Contiene 16% de grasa but rica y 27% prote', 'Leche parcialmente descremada', '', 0, 'alpura', 'openfoodfacts', 'unisex', 'baby'),
  ('Volledige zuigelingenvoeding', 'Volledige zuigelingenvoeding', 'baby', 'Lactose (melk), plantaardige oli n (high oleic zonnebloemolie, kokosolie. koolzaadolie, zonnebloemolie) galacto-oligosachariden (mal magere melk, soja-eiwit, wei concentraat (melk), tricalciumfosfaat, fructo-oligosachariden, kaliumchloride, natriumcitraat, olie van Crypthecodinium cohnii, magnesiumchloride, olie van Mortierella alpina, cholinechloride, L-ascorbinezuur, emulgator (sojalecithine), i', 'Lactose (melk)', '', 0, 'Nutrilon', 'openfoodfacts', 'unisex', 'baby'),
  ('Lait de suite 2eme age', 'Lait de suite 2eme age', 'baby', '', '', '', 0, 'Holle', 'openfoodfacts', 'unisex', 'baby'),
  ('Bl dilait 1er Age Bl dina', 'Bl dilait 1er Age Bl dina', 'baby', 'Lactos rum d min ralis  (lait) - Huiles v g tales (palme, colza, coprah, tournesol, mortierella alpina) - Lactose (lait) - Lait  cr m  - Galacto-oli - gosaccharides Cos) (lait) Prot ines de lactos rum concentr es (lait) - Fructo-oligo - saccharides (FOS) - Huile de poisson Chlorure de choline - Emulsifiant : l cithine de soja - Tau - rine - Nucl otides - Ino - sitol L-tryptophane L-carnitine - Vit', 'Lactos rum d min ralis  (lait) - Huiles v g tales (palme', '', 0, 'Bledilait', 'openfoodfacts', 'unisex', 'baby'),
  ('Lachs Mariniert', 'Lachs Mariniert', 'baby', '', '', '', 0, 'Bills', 'openfoodfacts', 'unisex', 'baby'),
  ('Nestle NAN Excellapro', 'Nestle NAN Excellapro', 'baby', 'Milk solids, Demineralised whey, Soyabean oil, Minerals, Low erucic rapeseed oil, High oleic sunflower oil, Coconut oil, Sunflower oil, Emulsifier (Soya lecithin), Human Milk Oligosaccharides'' (2''Fucosyllactose (2''FL) and Lacto-N-Neotetraose (LNnT), Choline bitartrate, Arachidonic acid (ARA) from Mortierella alpina oil, Docosahexaenoic acid (DHA) from Schizochytrium sp. oil, Vitamins, Amino acid (', 'Milk solids', '', 0, 'Nestl', 'openfoodfacts', 'unisex', 'baby'),
  ('Iglo Rahm Spinat', 'Rahmspinat, tiefgefroren', 'baby', '', '', '', 0, 'Iglo', 'openfoodfacts', 'unisex', 'baby'),
  ('Good Start Plus Ready to Feed', 'Good Start Plus Ready to Feed', 'baby', 'Water, Partially hydrolyzed reduced minerals whey protein concentrate, Corn maltodextrin, Lactose, Palm olein, Soybean oil, Coconut oil, High oleic safflower oil and/or high oleic sunflower oil, 2''-Fucosyllactose, Mortierella alpina oil  , Schizochytrium oil   , Taurine, Nucleotides (cytidine 5''-monophosphate, disodium uridine 5''-monophosphate, adenosine 5''-monophosphate, disodium guanosine 5''-mon', 'Water', '', 0, 'Nestl', 'openfoodfacts', 'unisex', 'baby'),
  ('Enfamil A+ Neuro Pro', 'Ready to Feed Infant Formula Milk-Based with Iron', 'baby', 'Water, Lactose, Contains three or more of the following (palm olein oil, coconut oil, soy oil, high oleic sunflower oil), Modified milk ingredients , Polydextrose, Galactooligosaccharide solids (GOS), Mono - and diglycerides, Mortierella alpina oil, Soy lecithin, Carrageenan, 2''-fucosyllactose, Schizochytrium sp. oil, Corn syrup solids, Taurine, L-carnitine, Mixed tocopherols, Ascorbyl palmitate,', 'Water', '', 0, 'Mead Johnson Nutrition', 'openfoodfacts', 'unisex', 'baby');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Bb milk dg 500ml', 'Bb milk dg 500ml', 'baby', '', '', '', 0, 'Buona', 'openfoodfacts', 'unisex', 'baby'),
  ('Similac Total Comfort Non-Gmo Infant Formula Powder 1.41Lb/22.5Oz Simplepac', 'Similac Total Comfort Non-Gmo Infant Formula Powder 1.41Lb/22.5Oz Simplepac', 'baby', 'Maltodextrin, Whey Protein Hydrolysate, High Oleic Safflower Oil, Sugar, Soy Oil, Coconut Oil, Galactooligosaccharides, Less Than 2% Of:, C. Cohnii Oil, M. Alpina Oil, Beta-Carotene, Lutein, Lycopene, Calcium Citrate, Potassium Phosphate, Calcium Phosphate, Magnesium Chloride, Salt, Potassium Citrate, Ascorbic Acid, Choline Chloride, Sodium Citrate, Potassium Chloride, Calcium Hydroxide, Ferrous S', 'Maltodextrin', '', 0, '', 'openfoodfacts', 'unisex', 'baby'),
  ('Jeeni Infants', 'Jeeni Infants', 'baby', '', '', '', 0, 'Jeeni Infants', 'openfoodfacts', 'unisex', 'baby'),
  ('Enfacare Neuro Pro', 'Infant formula', 'baby', '', '', '', 0, 'Enfamil, Mead Johnson Nutrition', 'openfoodfacts', 'unisex', 'baby'),
  ('MMS Infant Formula', 'MMS Infant Formula', 'baby', '', '', '', 0, 'British Life Sciences', 'openfoodfacts', 'unisex', 'baby');
