-- haircare: 94 products

INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Lola Cosmetics Meu Cacho Minha Vida Jelly Gel', 'Curl Defining Jelly Gel', 'haircare', 'Aqua (Water), Glycerin (Vegetable Derived), Acrylates/Beheneth-25 Methacrylate Copolymer, Oenocarpus Bataua Fruit Oil, Kappaphycus Alvarezii Extract, Eucheuma Spinosum Extract, Cocos Nucifera (Coconut) Fruit Extract, Chenopodium Quinoa Seed Extract, Carica Papaya Fruit Extract, Polyquaternium-10, Triethanolamine, Phenoxyethanol, Caprylyl Glycol.', 'Aqua (Water)', '', 0, 'Lola Cosmetics', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Batiste Nude Droogshampoo', 'Ben je op zoek naar een droogshampoo met een subtiele geur, die niet te overheersend is in combinatie met je parfum? Ga dan voor Batiste Nude Droogshampoo. Heerlijk naturel, maar met het vertrouwde effect van Batiste!', 'haircare', '', '', '', 0, 'Batiste', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Hydrating Conditioner', 'Hydrating Conditioner', 'haircare', 'Water (Aqua), Aloe Barbadensis Leaf Juice, Cetyl Alcohol, Cetrimonium Chloride, Cocos Nucifera (Coconut) Oil, Butyrospermum Parkii (Shea) Butter, Olea Europaea (Olive) Fruit Oil, Sesamum Indicum (Sesame) Seed Oil, Glycerin, Tocopherol (Vitamin E), Fragrance (Parfum)*, Isopropyl Alcohol, Citric Acid, Phenoxyethanol, Benzyl Alcohol, Limonene**, Citral**. *Natural Fragrance **Component of Natural Fragrance', 'Water (Aqua)', '', 0, 'sukin', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Fructis aloe Vera hair food', 'Fructis aloe Vera hair food', 'haircare', 'AQUA/WATER, CETEARYL ALCOHOL, GLYCERIN, ISOPROPYLMYRISTATE, GLYCINE SOJAOIL/SOYBEANOIL, STEARAMIDOPROPYLDIMETHYLAMINE, ALOEBARBADENSISLEAF JUICEPOWDER, HELIANTHUS ANNUUS SEED OIL/SUNFLOWER SEED OIL, GLYCERYL LINOLEATE, GLYCERYL LINOLENATE, GLYCERYL OLEATE, COCO-CAPRYLATE/CAPRATE, ASCORBYL GLUCOSIDE, HYDROXYPROPYL GUAR HYDROXYPROPYLTRIMONIUMCHLORIDE, CAPRYLYL GLYCOL, TARTARICACID, CETYLESTERS, TOCOPHEROL, SALICYLIC ACID, LINALOOL, GERANIOL, CITRONELLOL, BENZYL ALCOHOL, PARFUM/FRAGRANCE F.I.L. (F.', 'AQUA/WATER', '', 0, 'L''Or al, L''Oreal Consumer products, Garnier', 'openbeautyfacts', 'unisex', 'treatment'),
  ('Keratin sleek', 'Keratin sleek', 'haircare', 'AQUA/WATER, CETEARYL ALCOHOL, STEARAMIDOPROPYL DIMETHYLAMINE, ISOPROPYL MYRISTATE, CETYL ESTERS, HELIANTHUS ANNUUS SEED OIL/SUNFLOWER SEED OIL, ARGANIA SPINOSA KERNEL OIL, BUTYROSPERMUM PARKII BUTTER/SHEA BUTTER, HYDROLYZED CORN PROTEIN. HYDROLYZED SOY PROTEIN, HYDROLYZED WHEAT PROTEIN, CAPRYLYL GLYCOL, CITRIC ACID, TARTARIC ACID, PHENOXYETHANOL, BENZOIC ACID, LINALOOL, AMYL CINNAMAL, HEXYL CINNAMAL, BENZYL ALCOHOL PARFUM/FRAGRANCE.(F.I.L. 270055972/1).', 'AQUA/WATER', '', 0, 'L''Or al, L''Oreal Consumer products, Garnier', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Herbel Essences Step 4', 'haire caire cream', 'haircare', 'Aqua, Dimenthicone, Cetyl Alchol, Stearamidoproply Dimethylamine, Stearyl Alcohool, Hydroxyethlcellulose, Quantenium-18, Phenoxyethanol, Benzyl Alcohol, PEG-2M, Parfum, Cetearyl Alcohol, Methylparaben, Propylparapen, Oleyl Alcohol, Glyceryl Stearate, Polysorbate 60, Lysine HCI, Benzyl Salicylate, Citric Acid, EDTA, Alcohol, Hexyl Cinnamal, Limonene, Butylene, Glycol, Geraniol, Histidine, Silica, Aloe Barbadensis Leaf Juice, Persea Gratissima Oil, Citronrllol, Alpha-Isomethyl lonone, Linalool, Al', 'Aqua', '', 0, NULL, 'openbeautyfacts', 'unisex', 'hair-care'),
  ('L''Or al Paris Elseve Color Vive Turuncula ma Kar t Mor ampuan', 'L''Or al Paris Elseve Color Vive Turuncula ma Kar t Mor ampuan', 'haircare', 'Aqua / Water, Sodium Laureth Sulfate, Coco-Betaine, Glycol Distearate, Cocamide MIPA, CI 60730 / Acid Violet 43, Sodium Lauryl Sulfate, Sodium Chloride, Sodium Benzoate, Sodium Hydroxide, Trideceth-6, Iris Florentina Root Extract, Polyquaternium-7, Polyquaternium-10, Salicylic Acid, Limonene, Linalool, Benzyl Salicylate, Benzyl Alcohol, Benzophenone-4, Amodimethicone, Alpha-Isomethyl Ionone, Carbomer, Citric Acid, Citronellol, Cetrimonium Chloride, Butylene Glycol, Coumarin, Hexylene Glycol, Amy', 'Aqua / Water', '', 0, 'L''Or al, L''Oreal Consumer products, L''Or al Paris, Elseve', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Duru Zeytinya & Kolajen ampuan', 'Duru Zeytinya & Kolajen ampuan', 'haircare', '', '', '', 0, 'Duru', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Hobby Do al Ya zleri Argan Ya ve Papatya i e i zl ampuan', 'Hobby Do al Ya zleri Argan Ya ve Papatya i e i zl ampuan', 'haircare', '', '', '', 0, 'Hobby', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Assos Sebovium Forte ampuan', 'Assos Sebovium Forte ampuan', 'haircare', 'Aqua, Epilobium Angustifolium Extract, Panthenol, Cocos Nucifera Oil, Juniperus Communis Tar, Selenium Sulfide, Salicylic Acid, Propylene Glycol, Sulfur, Piroctone Olamine', 'Aqua', '', 0, 'Assos, Sebovium', 'openbeautyfacts', 'unisex', 'shampoo');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Liviton Professional %6 20 Vol Oksidan Krem', 'Liviton Professional %6 20 Vol Oksidan Krem', 'haircare', '', '', '', 0, 'Liviton', 'openbeautyfacts', 'unisex', 'colour'),
  ('Yves Rocher K r lma Kar t Is Koruyucu G lendirici Serum&quot;', 'Yves Rocher K r lma Kar t Is Koruyucu G lendirici Serum&quot;', 'haircare', 'Aqua/Water/Eau, Behentrimonium Chloride, Isopropyl Myristate, Stearyl Alcohol, Cetyl Alcohol, Simmondsia Chinensis (Jojoba) Seed Oil, Parfum/Fragrance, Isopropyl Alcohol, Sodium Benzoate, Fructooligosaccharides, Inulin, Citric Acid, Panthenol, Hydrolyzed Hibiscus Esculentus Extract, Benzyl Alcohol, Dextrin', 'Aqua/Water/Eau', '', 0, 'Yves Rocher', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('L''huile merveilleuse aux huiles d''argan et de camelia', 'Huile pour cheveux', 'haircare', 'cyclopentasiloxane, dimethiconol, argania spinosa oil/argania spinosa kernel oil, ethylhexyl methoxycinnamate, camellia oleifera seed oil, limonene, linalool, benzyl alcohol, geraniol, citronellol, hexyl cinnamal, parfum / fragrance. (FIL C51607/1)', 'cyclopentasiloxane', '', 0, 'L''Or al, L''Oreal Consumer products, Garnier, Ultra Doux', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Elidor 7''si 1 Arada Sa G zelle tirici Durulanmayan Bak m Kremi', 'Elidor 7''si 1 Arada Sa G zelle tirici Durulanmayan Bak m Kremi', 'haircare', 'Aqua, Cetearyl Alcohol, Stearamidopropyl Diethylamine, Dimethiconol, Glycerin, Parfum, Lactic Acid, Sodium Benzoate, Paraffinum Liquidum, Petrolatum, Disodium EDTA, TEA-Dodecylbenzenesulfonate, Caprylic/Capric Triglyceride, PEI-45 TMP Xylene Diisocyanate Crosspolymer, Bentonite, Caprylyl Glycol, Polyquaternium-4, Sodium Polystyrene Sulfonate, Hydrolyzed Collagen, Cellulose Gum, Alpha-Isomethyl Ionone, Benzyl Alcohol, Benzyl Salicylate, Citronellol, Geraniol, Hexyl Cinnamal, Limonene, Linalool', 'Aqua', '', 0, 'Elidor', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('M NOX L FORTE %5 Deri Spreyi, zelti', 'M NOX L FORTE %5 Deri Spreyi, zelti', 'haircare', 'Minoxidil, Propylene Glycol, Alcohol, Citric Acid, Deionized Water', 'Minoxidil', '', 0, 'Minoxil Forte', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Tala Y lan Ya Sa Bak m Ya', 'Tala Y lan Ya Sa Bak m Ya', 'haircare', 'Y lan ya , bitkisel ekstrakt, E vitamini, D-pantenol', 'Y lan ya', '', 0, 'Tala', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('True Bee Daily Dream Biberiye Kompleks Ya', 'True Bee Daily Dream Biberiye Kompleks Ya', 'haircare', '', '', '', 0, 'True Bee', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Elidor Brezilya Keratin Terapisi Is ile Aktifle en Keratin Bak m K r', 'Elidor Brezilya Keratin Terapisi Is ile Aktifle en Keratin Bak m K r', 'haircare', 'Aqua, Cyclopentasiloxane, Amodimethicone, Stearamidopropyl Dimethylamine, Cetyl Alcohol, Caprylic/Capric Triglyceride, Polyquaternium-28, Cyclohexasiloxane, Phenoxyethanol, Polyquaternium Crosspolymer-3, Dimethicone, Glycerin, Paraffinum Liquidum, Parfum, Aspartic Acid, Distearoylethyl Dimonium Chloride, Cetearyl Alcohol, Acrylamidopropyltrimonium Chloride/Acrylamide Copolymer, PVM/MA Copolymer, Sorbitan Oleate, PPG-1 Trideceth-6, Disodium EDTA, C11-13 Isoparaffin, Sodium Hydroxide, Caprylyl Gly', 'Aqua', '', 0, 'Unilever, Elidor', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Head & Shoulders Men 2 in 1 Anti-Hair Fall Anti-Dandruff Shampoo', 'Shampoo', 'haircare', 'Aqua, Sodium Laureth Sulfate, Sodium Lauryl Sulfate, Sodium Chloride, Sodium Xylenesulfonate, Cocamidopropyl Betaine, Glycol Distearate, Sodium Citrate, Parfum, Piroctone Olamine, Dimethiconol, Citric Acid, Dimethicone, Sodium Salicylate, Sodium Benzoate, Menthol, Guar Hydroxypropyltrimonium Chloride, TEA-Dodecylbenzenesulfonate, Tetrasodium EDTA, Sodium Hydroxide, Caffeine, Trideceth-10, Limonene, Linalool, CI 19140, Triethylene Glycol, Propylene Glycol, Benzyl Alcohol, CI 42090.', 'Aqua', '', 0, 'Head & Shoulders', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Inecto Naturals Super Moisturising Coconut Hair Mask', 'Inecto Naturals Super Moisturising Coconut Hair Mask', 'haircare', 'Aqua (Water), Cetearyl Alcohol, Helianthus Annuus (Sunflower) Seed Oil, Stearic Acid, Glycerin, Cetrimonium Chloride, Ceteareth-20, C12-15 Alkyl Benzoate, Behentrimonium Methosulfate, Coco Glucoside, Cocos Nucifera (Coconut) Oil, Hydrolyzed Wheat Protein, Hydrolyzed Wheat Starch, Polyquaternium-37, Parfum, Paraffinum Liquidum, Ethylhexylglycerin, PPG-1 Trideceth-6, Sorbitan Oleate, Potassium Sorbate, Triethanolamine, Phenoxyethanol.', 'Aqua (Water)', '', 0, 'Inecto, Inecto Naturals', 'openbeautyfacts', 'unisex', 'treatment');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('L Or al Paris Casting Cr me Gloss 400 Kestane Sa Boyas', 'L Or al Paris Casting Cr me Gloss 400 Kestane Sa Boyas', 'haircare', 'Aqua / Water, Cetearyl Alcohol, Propylene Glycol, Deceth-3, Laureth-12, Ethanolamine, Oleth-30, Lauric Acid, Polyquaternium-6, Glycol Distearate, Toluene-2,5-Diamine, Hexadimethrine Chloride, Silica Dimethyl Silylate [Nano] / Silica Dimethyl Silylate, CI 77491 / Iron Oxides, CI 77891 / Titanium Dioxide, 2,4-Diaminophenoxyethanol HCl, m-Aminophenol, Ascorbic Acid, Mica, Thiolactic Acid, Thioglycerin, 2-Methylresorcinol, N,N-Bis(2-Hydroxyethyl)-p-Phenylenediamine Sulfate, Carbomer, Resorcinol, EDT', 'Aqua / Water', '', 0, 'L''Or al, L''Oreal Consumer products, L''Or al Paris', 'openbeautyfacts', 'unisex', 'colour'),
  ('Head & Shoulders Klasik Bak m Kepe e Kar Etkili ampuan', 'Head & Shoulders Klasik Bak m Kepe e Kar Etkili ampuan', 'haircare', 'Aqua, Sodium Laureth Sulfate, Sodium Lauryl Sulfate, Sodium Chloride, Sodium Xylenesulfonate, Cocamidopropyl Betaine, Glycol Distearate, Sodium Citrate, Parfum, Piroctone Olamine, Sodium Benzoate, Dimethiconol, Citric Acid, Sodium Salicylate, Guar Hydroxypropyltrimonium Chloride, Dimethicone, Hexyl Cinnamal, Linalool, Tetrasodium EDTA, Sodium Hydroxide, TEA-Dodecylbenzenesulfonate, Trideceth-10, Polyquaternium-76, Benzyl Alcohol, Triethylene Glycol, Propylene Glycol, CI 42090, CI 17200.', 'Aqua', '', 0, 'Head & Shoulders', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Green Therapy Hair Dye Cream 6.3 Hazelnut Shell', 'Green Therapy Hair Dye Cream 6.3 Hazelnut Shell', 'haircare', 'aqua/water, sodium coco-sulfate, ethanolamine, myristyl alcohol, cetearyl alcohol, cocamide mea, cocamide mipa, cocamidopropyl betaine, toluene-2,5-diamine sulfate, oleth-20, tietrasodium edta, sodium sulfite, bisamino peg/ppg-41/3 aminoethyl pg-propyl dimethicone, 4chlororesorcinol, vitis vinifera seed oil, 2-methylresorinol, oleth-5 phosphate, p-aminophenol, argania spinosa oil&quot;, hydrolyzed keratin, sodium cocoyl hydrolyzed wheat protein, dioleyl phosphate, erythorbic acid, butyrospermum ', 'aqua/water', '', 0, 'Green Therapy', 'openbeautyfacts', 'unisex', 'colour'),
  ('Pantene Do al Sentez G ve Parlakl k 3'' 1 Arada ampuan', 'Pantene Do al Sentez G ve Parlakl k 3'' 1 Arada ampuan', 'haircare', '', '', '', 0, 'Pantene', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('L Or al Paris Elseve Hydra [Hyaluronic] Nemi Hapseden Sa Bak m Kremi', 'L Or al Paris Elseve Hydra [Hyaluronic] Nemi Hapseden Sa Bak m Kremi', 'haircare', 'Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Cetyl Esters, Lactic Acid, Sodium Hyaluronate, Phenoxyethanol, Trideceth-6, Chlorhexidine Digluconate, Limonene, Amodimethicone, Isopropyl Alcohol, Potassium Hydroxide, Cetrimonium Chloride, Parfum.', 'Aqua', '', 0, 'L''Or al, L''Oreal Consumer products, L''Or al Paris, Elseve', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Hindistan Cevizi Ya', 'Hindistan Cevizi Ya', 'haircare', 'Hindistan cevizi ya', 'Hindistan cevizi ya', '', 0, 'Naturoil', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('L Or al Paris Elseve 3 Mucizevi Kil Banyo ncesi Kil Maskesi', 'L Or al Paris Elseve 3 Mucizevi Kil Banyo ncesi Kil Maskesi', 'haircare', 'PEG-8, Argilla, Magnesium Aluminum Silicate, Aqua / Water, Kaolin, Glycerin, Olea Europaea Oil / Olive Fruit Oil, Cetearyl Alcohol, Benzyl Alcohol, Parfum / Fragrance, Stearyl Alcohol, Stearic Acid, PEG-8 Isostearate, Salicylic Acid, Palmitic Acid, Xanthan Gum, Linalool, Benzyl Salicylate, Montmorillonite, Caprylyl Glycol.', 'PEG-8', '', 0, 'L''Or al, L''Oreal Consumer products, L''Or al Paris, Elseve', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Davines New Colour Sa Boyas 6.1', 'Davines New Colour Sa Boyas 6.1', 'haircare', '', '', '', 0, 'Davines', 'openbeautyfacts', 'unisex', 'colour'),
  ('Bioblas Botanic Oils Sar msakl ampuan', 'Bioblas Botanic Oils Sar msakl ampuan', 'haircare', '', '', '', 0, 'Bioblas', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Shampoing solide Acorn', 'Shampoing solide Acorn', 'haircare', 'SCI (hindistan cevizi ya ndan elde edilmi temizleyici), Coco Betaine (hindistan cevizi ya ndan elde edilir), Bitkisel Keratin, pek Proteini, Panthenol, Kakao Ya , Ard Katran , Tunceli Da Sar msa z , Palamut z , Ye il Kil, Biberiye U ucu Ya , Ard U ucu Ya , Sitrik Asit.', 'SCI (hindistan cevizi ya ndan elde edilmi temizleyici)', '', 0, 'Jil Do al', 'openbeautyfacts', 'unisex', 'shampoo');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Clear Men Legend By CR7 Cristiano Ronaldo Kepe e Kar Etkili ampuan', 'Clear Men Legend By CR7 Cristiano Ronaldo Kepe e Kar Etkili ampuan', 'haircare', 'Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Parfum, Sodium Benzoate, Dimethiconol, Piroctone Olamine, Citric Acid, Carbomer, Dimethicone, Menthol, Guar Hydroxypropyltrimonium Chloride, Sodium Hydroxide, Mica, Helianthus Annuus (Sunflower) Seed Oil, Disodium EDTA, Acrylamidopropyltrimonium Chloride/Acrylamide Copolymer, Glycerin, TEA-Dodecylbenzenesulfonate, TEA-Sulfate, Laureth-23, Poloxamer 407, PPG-9, Phenoxyethanol, Laureth-4, PEG-4, Glycine, Niacinamide, Sea Salt, ', 'Aqua', '', 0, 'Clear, Clear Men', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Bee Beauty Biotin & Keratin Sa Bak m Maskesi', 'Bee Beauty Biotin & Keratin Sa Bak m Maskesi', 'haircare', '', '', '', 0, 'Bee Beauty', 'openbeautyfacts', 'unisex', 'treatment'),
  ('L Or al Paris Elseve Hydra [Hyaluronic] Nem ile Dolgunla t ran Serum', 'L Or al Paris Elseve Hydra [Hyaluronic] Nem ile Dolgunla t ran Serum', 'haircare', 'Aqua / Water, Quaternium-87, Cocos Nucifera Oil / Coconut Oil, Sodium Benzoate, Sodium Hyaluronate, Stearyl Alcohol, PPG-1 Trideceth-6, Behentrimonium Chloride, Polyquaternium-37, Polysorbate 20, Polyquaternium-11, Limonene, Candelilla Cera / Candelilla Wax, Pentaerythrityl Tetra-di-t-butyl Hydroxyhydrocinnamate, Propylene Glycol Dicaprylate/Dicaprate, Coumarin, Glycine Soja Oil / Soybean Oil, Parfum / Fragrance.', 'Aqua / Water', '', 0, 'L''Or al, L''Oreal Consumer products, L''Or al Paris, Elseve', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Morfose F n Suyu', 'Morfose F n Suyu', 'haircare', '', '', '', 0, 'Morfose', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('ISANA Professional Argan Ya erikli Sa Bak m Ya', 'ISANA Professional Argan Ya erikli Sa Bak m Ya', 'haircare', 'Isododecane, C11-13 Isoalkane, Isohexadecane, Dimethiconol, Helianthus Annuus Hybrid Oil, Dimethicone, Argania Spinosa Kernel Oil, Helianthus Annuus Seed Oil, Trisiloxane, Parfum, Linalool, Citral, Limonene, CI 40800.', 'Isododecane', '', 0, 'ISANA', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Old Spice Bearglove Erkek Du Jeli ve ampuan', 'Old Spice Bearglove Erkek Du Jeli ve ampuan', 'haircare', 'Aqua, Sodium Lauryl Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Parfum, Sodium Benzoate, Sodium Citrate, Benzyl Alcohol, Sodium Xylenesulfonate, Sodium Salicylate, Citric Acid, Disodium EDTA, Sodium Hydroxide, Limonene, Hexyl Cinnamal, Linalool, Alpha-Isomethyl Ionone, CI 42090, CI 19140.', 'Aqua', '', 0, 'Old Spice', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('L Or al Paris Elseve Mucizevi Ya Sa G zelle tirici Krem', 'L Or al Paris Elseve Mucizevi Ya Sa G zelle tirici Krem', 'haircare', 'Aqua / Water, Cetearyl Alcohol, Cocos Nucifera Oil / Coconut Oil, Cetyl Esters, Cetyl Alcohol, Amodimethicone, Behentrimonium Methosulfate, CI 15985 / Yellow 6, CI 19140 / Yellow 5, Lactic Acid, Hydrogenated Jojoba Oil, Phenoxyethanol, Trideceth-6, Anise Alcohol, Chlorhexidine Digluconate, Limonene, Simmondsia Chinensis Seed Oil / Jojoba Seed Oil, Linalool, Caramel, Cetrimonium Chloride, Coumarin, Hexyl Cinnamal, Parfum / Fragrance.', 'Aqua / Water', '', 0, 'L''Or al, L''Oreal Consumer products, L''Or al Paris', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Head & Shoulders Menthol Fresh Kepe e Kar ampuan', 'Head & Shoulders Menthol Fresh Kepe e Kar ampuan', 'haircare', 'Aqua, Sodium Laureth Sulfate, Sodium Xylenesulfonate, Cocamidopropyl Betaine, Sodium Citrate, Menthol, Piroctone Olamine, Sodium Chloride, Parfum, Citric Acid, Guar Hydroxypropyltrimonium Chloride, Dimethiconol, Dimethicone, Sodium Benzoate, Sodium Salicylate, Tetrasodium EDTA, TEA-Dodecylbenzenesulfonate, Hexyl Cinnamal, Sodium Hydroxide, Linalool, Mentha Arvensis Leaf/Stem Oil, Mentha Piperita Oil, Trideceth-10, Hexamethylindanopyran, Linalyl Acetate, Acetic Acid, Benzyl Alcohol, Propylene Gly', 'Aqua', '', 0, 'Head & Shoulders', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Restorex Keratin & Argan Onar c Sa Bak m Maskesi', 'Restorex Keratin & Argan Onar c Sa Bak m Maskesi', 'haircare', 'Aqua / Water, Cetearyl Alcohol, Cetyl Alcohol, Behentrimonium Chloride, Parfum / Fragrance, Argania Spinosa (Argan) Kernel Oil, Hydrolyzed Keratin, Glycerin, Panthenol, Guar Hydroxypropyltrimonium Chloride, Amodimethicone, Benzyl Alcohol, Trideceth-12, Linalool, Hydroxycitronellal, Hexyl Cinnamal, D-Limonene, Geraniol, Methylchloroisothiazolinone, Methylisothiazolinone, CI 42090, CI 19140.', 'Aqua / Water', '', 0, 'Restorex', 'openbeautyfacts', 'unisex', 'treatment'),
  ('Elidor Summer Rescue S.O.S. ampuan Hibiskus, pek Proteini & C Vitamini', 'Elidor Summer Rescue S.O.S. ampuan Hibiskus, pek Proteini & C Vitamini', 'haircare', 'Aqua, Sodium Laureth Sulfate, Sodium Chloride, Cocamidopropyl Betaine, Dimethiconol, Parfum, Glycerin, Sodium Benzoate, Carbomer, Citric Acid, TEA-Dodecylbenzenesulfonate, Guar Hydroxypropyltrimonium Chloride, TEA-Sulfate, Hydroxypropyl Methylcellulose, Sodium Hydroxide, Disodium EDTA, Mica, PEG-45M, Phenoxyethanol, PPG-9, Silica, Propylene Glycol, Hibiscus Sabdariffa Flower Extract, Hydrolyzed Silk, Tocopheryl Acetate, Hexyl Cinnamal, Limonene, Linalool, CI 77891.', 'Aqua', '', 0, 'Elidor', 'openbeautyfacts', 'unisex', 'shampoo');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('L Or al Paris Elseve Komple Diren D k lme Kar t Bak m ampuan', 'L Or al Paris Elseve Komple Diren D k lme Kar t Bak m ampuan', 'haircare', 'Aqua / Water, Sodium Laureth Sulfate, Glycol Distearate, Sodium Chloride, Cocamidopropyl Betaine, Dimethicone, Guar Hydroxypropyltrimonium Chloride, Diaminopyrimidine Oxide, Cocamide MEA, Coco-Betaine, Sodium Benzoate, Sodium Hydroxide, Steareth-6, Phenoxyethanol, Acetic Acid, Arginine, PEG-100 Stearate, Trideceth-10, Trideceth-3, Salicylic Acid, Limonene, Fumaric Acid, Amodimethicone, Biotin, Carbomer, Citric Acid, Hexylene Glycol, Parfum / Fragrance.', 'Aqua / Water', '', 0, 'L''Or al, L''Oreal Consumer products, L''Or al Paris, Elseve', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Dalin Kolay Tarama Sa Spreyi', 'Bebek ve ocuklar i in durulanmayan kolay tarama sa spreyi', 'haircare', 'Aqua, Polyquaternium-11, Amodimethicone, Panthenol, Prunus Amygdalus Dulcis Seed Extract, Glycerin, Parfum, Sodium Benzoate, Citric Acid, Potassium Sorbate, Trideceth-12, Cetrimonium Chloride, Disodium EDTA', 'Aqua', '', 0, 'Dalin', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Watsons Kuru ampuan Fresh', 'Ya lanmaya e ilimli sa lar i in fresh kokulu kuru ampuan', 'haircare', 'Butane, Propane, Isobutane, Alcohol Denat., Oryza Sativa Starch, Parfum, Cyclopentasiloxane, Distearyldimonium Chloride, Benzophenone-4, Hexyl Cinnamal, Alpha-Isomethyl Ionone, Linalool, Geraniol, Citronellol, Benzyl Salicylate, Limonene', 'Butane', '', 0, 'Watsons', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Naturals by Watsons Aloe Vera Kepek Kar t ampuan', 'Naturals by Watsons Aloe Vera Kepek Kar t ampuan', 'haircare', 'Aqua, Ammonium Lauryl Sulfate, Glycerin, Cocamidopropyl Betaine, Cocamide MEA, Propylene Glycol, Phenoxyethanol, Sodium Chloride, Polysorbate 20, Parfum, Chlorphenesin, Polyquaternium-10, Climbazole, Polyquaternium-7, Sodium Benzoate, Butyl Methoxydibenzoylmethane, Citric Acid, Trisodium Ethylenediamine Disuccinate, Aloe Barbadensis (Aloe Vera) Leaf Juice, Crambe Abyssinica (Abyssinian) Seed Oil, Persea Gratissima (Avocado) Oil, Helianthus Annuus (Sunflower) Seed Oil, Butylene Glycol, Propanedio', 'Aqua', '', 0, 'Naturals by Watsons', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Atomy Scalpcare Hair Shampoo', 'Atomy Scalpcare Hair Shampoo', 'haircare', 'Aqua, Ammonium Laureth Sulfate, Ammonium Lauryl Sulfate, Glycerin, 1,2-Hexanediol, Acacia Concinna Fruit Extract, Achillea Millefolium Extract, Alchemilla Vulgaris Extract, Alcohol, Althaea Officinalis Root Extract, Ammonium Sulfate, Arnica Montana Flower Extract, Artemisia Absinthium Extract, Borago Officinalis Extract, Butylene Glycol, Calendula Officinalis Flower Extract, Cetearyl Alcohol, Chamomilla Recutita Flower Extract, Citric Acid, Cocamide MEA, Cocamidopropyl Betaine, Disodium EDTA, Ec', 'Aqua', '', 0, 'Atomy', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Pantene Pro-V Miracles Hydra Glow Kuru Sa U lar na Elveda Durulanmayan G nd z Serumu', 'Pantene Pro-V Miracles Hydra Glow Kuru Sa U lar na Elveda Durulanmayan G nd z Serumu', 'haircare', 'Aqua, Dimethicone, Paraffinum Liquidum, Phenoxyethanol, Betaine, Benzyl Alcohol, Polyacrylamide, C13-14 Alkane, Parfum, Ethylhexylglycerin, Laureth-7, Panthenol, Panthenyl Ethyl Ether, Limonene, Histidine, Sodium Hyaluronate, Adansonia Digitata Seed Oil, Geraniol, Hydroxycitronellal, Citric Acid, Biotin, Tocopherol', 'Aqua', '', 0, 'Pantene', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('ISANA Professional Nemlendirici ve Yo un Bak m Sa Maskesi', 'ISANA Professional Nemlendirici ve Yo un Bak m Sa Maskesi', 'haircare', 'Aqua, Cetearyl Alcohol, Dicaprylyl Ether, Coco-Caprylate, Behentrimonium Chloride, Aloe Barbadensis Leaf Juice, Prunus Amygdalus Dulcis Oil, Panthenol, Glycerin, Butylene Glycol, Oryza Sativa Bran Oil, Nelumbo Nucifera Flower Extract, Oryza Sativa Extract, Stearamidopropyl Dimethylamine, Tocopherol, Isopropyl Alcohol, Citric Acid, Parfum, Benzyl Alcohol, Linalool, Benzyl Salicylate, Sorbic Acid, Sodium Benzoate, Potassium Sorbate', 'Aqua', '', 0, 'ISANA, ISANA Professional', 'openbeautyfacts', 'unisex', 'treatment'),
  ('K rastase Fusio-Scrub Scrub Apaisant Hassas Sa Derisi in Peeling', 'K rastase Fusio-Scrub Scrub Apaisant Hassas Sa Derisi in Peeling', 'haircare', 'Aqua / Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Cellulose Acetate, Sodium Chloride, Sodium Benzoate, Capryloyl Glycine, Sodium Hydroxide, Polyquaternium-10, Salicylic Acid, Linalool, Hexyl Cinnamal, Citrus Aurantium Dulcis Oil / Orange Peel Oil, Sodium Acetate, Isopropyl Alcohol, Citronellol, Citric Acid, Parfum / Fragrance', 'Aqua / Water', '', 0, 'K rastase', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Life In Sar msak Ya', 'Life In Sar msak Ya', 'haircare', 'Sar msak ya (Garlic oil)', 'Sar msak ya (Garlic oil)', '', 0, 'Life In', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Gliss Oil Nutritive S v Sa Bak m Kremi', 'Gliss Oil Nutritive S v Sa Bak m Kremi', 'haircare', '', '', '', 0, 'Henkel, Schwarzkopf, Gliss', 'openbeautyfacts', 'unisex', 'conditioner');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Gliss Serum Deep Repair Onar c S v Sa Bak m Kremi', 'Gliss Serum Deep Repair Onar c S v Sa Bak m Kremi', 'haircare', '', '', '', 0, 'Gliss', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Urban Care Style Guide Elastic Curl Sa J lesi', 'Bukle belirginle tirici esnek tutu lu sa j lesi', 'haircare', 'Aqua/Water, Triethanolamine, VP/VA Copolymer, Carbomer, Hydrolyzed Corn Protein, Hydrolyzed Soy Protein, Hydrolyzed Wheat Protein, Leuconostoc/Radish Root Ferment Filtrate, PEG-40 Hydrogenated Castor Oil, DMDM Hydantoin, Parfum, Benzyl Benzoate, Limonene, Hexyl Cinnamal, Benzyl Salicylate, Linalool', 'Aqua/Water', '', 0, 'Urban Care', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Capitol ampuan 700 ml Normal Sa lar in', 'Capitol ampuan 700 ml Normal Sa lar in', 'haircare', '', '', '', 0, 'Capitol', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('MinoXsi Hair Therapy Professional Multi-Peptide Sa Yo unla t r c Serum', 'Sa yo unlu u i in oklu peptit sa serumu', 'haircare', 'Aqua, Glycerin, Niacinamide, Thiamine HCl, Pantothenic Acid, Pyridoxine HCl, Butylene Glycol, Pisum Sativum Sprout Extract, Sodium Hyaluronate, PEG-40 Hydrogenated Castor Oil, Tocopheryl Acetate, Phenoxyethanol, Apigenin, Oleanolic Acid, Biotinoyl Tripeptide-1, Polysorbate 20, Folic Acid, Ascorbic Acid, Zinc Sulfate, Ethylhexylglycerin', 'Aqua', '', 0, 'MinoXsi', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Seven Pigments / Natulika Organic Sa Boyas 7.07 Konyak', 'Seven Pigments / Natulika Organic Sa Boyas 7.07 Konyak', 'haircare', '', '', '', 0, 'Seven Pigments', 'openbeautyfacts', 'unisex', 'colour'),
  ('Pantene Pro-V Temel Bak m 3'' 1 Arada ampuan', 'Pantene Pro-V Temel Bak m 3'' 1 Arada ampuan', 'haircare', 'Aqua, Sodium Laureth Sulfate, Sodium Citrate, Sodium Xylenesulfonate, Sodium Lauryl Sulfate, Glycol Distearate, Cocamidopropyl Betaine, Sodium Chloride, Dimethicone, Cocamide MEA, Parfum, Sodium Benzoate, Stearyl Alcohol, Citric Acid, Sodium Salicylate, Cetyl Alcohol, Glycerin, Guar Hydroxypropyltrimonium Chloride, Polyquaternium-6, Sodium Hydroxide, Tetrasodium EDTA, Panthenol, Panthenyl Ethyl Ether, Histidine, Hexyl Cinnamal.', 'Aqua', '', 0, 'Pantene', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Hobby Biotin Vitamin Kompleks Hyaluronik Asit ampuan 850 ml', 'Hobby Biotin Vitamin Kompleks Hyaluronik Asit ampuan 850 ml', 'haircare', 'Kolojen, biotin', 'Kolojen', '', 0, 'Hobby', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Dalin Bebek ampuan', 'Dalin Bebek ampuan', 'haircare', 'Aqua, Decyl Glucoside, Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, PEG-120 Methyl Glucose Dioleate, Coco-Glucoside, Glyceryl Oleate, Parfum, Sodium Benzoate, Citric Acid, Potassium Sorbate, Disodium EDTA.', 'Aqua', '', 0, 'Dalin', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Pantene G ve Parlakl k ampuan', 'Pantene G ve Parlakl k ampuan', 'haircare', 'Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Sodium Xylenesulfonate, Parfum, Citric Acid, Sodium Benzoate, Sodium Citrate, Sodium Salicylate, Dimethiconol, Guar Hydroxypropyltrimonium Chloride, TEA-Dodecylbenzenesulfonate, Sodium Hydroxide, Tetrasodium EDTA, Panthenol, Panthenyl Ethyl Ether, Laureth-23, Hexyl Cinnamal, Histidine.', 'Aqua', '', 0, 'Pantene', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Isana Sa Bak m K r Argan Ya 25 ml', 'Isana Sa Bak m K r Argan Ya 25 ml', 'haircare', 'Aqua, Dicaprylyl Ether, Cetyl Alcohol, Cetrimonium Chloride, Stearamidopropyl Dimethylamine, Stearyl Alcohol, Argania Spinosa Kernel Oil, Phenoxyethanol, Parfum, Potassium Sorbate, Vaccinium Macrocarpon Seed Oil, Citric Acid, Niacinamide, Benzoic Acid, Dehydroacetic Acid, Ethylhexylglycerin, Tocopherol.', 'Aqua', '', 0, 'Isana', 'openbeautyfacts', 'unisex', 'treatment');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Vini jr', 'Vini jr', 'haircare', 'Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Parfum, Sodium Benzoate, Menthol, Dimethiconol, Piroctone Olamine, Citric Acid, Carbomer, Dimethicone, Guar Hydroxypropyltrimonium Chloride, Sodium Hydroxide, Mica, Helianthus Annuus (Sunflower) Seed Oil, Acrylamidopropyltrimonium Chloride/Acrylamide Copolymer, Disodium EDTA, Glycerin, TEA-Dodecylbenzenesulfonate, TEA-Sulfate, Glycine, Niacinamide, Laureth-23, Poloxamer 407, PPG-9, Phenoxyethanol, Laureth-4, PEG-4, Propylene ', 'Aqua', '', 0, 'Clear', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Head & Shoulders Classic Clean 2 in 1 Shampoo', 'Head & Shoulders Classic Clean 2 in 1 Shampoo', 'haircare', 'Aqua, Sodium Laureth Sulfate, Sodium Xylenesulfonate, Cocamidopropyl Betaine, Sodium Citrate, Parfum, Dimethiconol, Citric Acid, Cocamide MEA, Glycol Distearate, Piroctone Olamine, Sodium Chloride, Dimethicone, Guar Hydroxypropyltrimonium Chloride, Sodium Benzoate, TEA-Dodecylbenzenesulfonate, Sodium Salicylate, Hexyl Cinnamal, Linalool, Tetrasodium EDTA, Trideceth-10, Sodium Hydroxide, Glycerin, Niacinamide, Panthenol, Tocopheryl Acetate, Acetic Acid, Benzyl Alcohol, Triethylene Glycol, Propyle', 'Aqua', '', 0, 'Head & Shoulders', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Bali Curls Bukle Belirginle tirici J le', 'Bali Curls Bukle Belirginle tirici J le', 'haircare', 'Aqua, Glycerin, Hydrolyzed Corn Starch, Xanthan Gum, Polyglyceryl-4 Caprate, Polyglyceryl-6 Caprylate, Propylene Glycol, Betaine, Panthenol, Sodium Benzoate, Parfum, Magnesium Sulfate, Gellan Gum, Potassium Sorbate, Citric Acid, Sodium Citrate, Linalool, Limonene, Biosaccharide Gum-1, Sodium Levulinate, Geraniol, Glyceryl Caprylate, Linum Usitatissimum Seed Extract, Sodium Anisate, Cananga Odorata Flower Extract.', 'Aqua', '', 0, 'Bali Curls', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Dax Supergro Sa Bak m Ya', 'Dax Supergro Sa Bak m Ya', 'haircare', 'Petrolatum, Fragrance (Parfum), Prunus Amygdalus Dulcis (Sweet Almond) Oil, Persea Gratissima (Avocado) Oil, Helianthus Annuus (Sunflower) Seed Oil, Simmondsia Chinensis (Jojoba) Seed Extract, Sesamum Indicum (Sesame) Seed Oil, Triticum Vulgare (Wheat) Germ Oil, Carthamus Tinctorius (Safflower) Flower Extract, Gossypium Herbaceum (Cotton) Seed Oil, Coumarin, Benzyl Benzoate.', 'Petrolatum', '', 0, 'Dax', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Vichy Dercos Anti-Dandruff Kepek Kar t ampuan 390 ml - Normal ve Ya l Sa lar', 'Vichy Dercos Anti-Dandruff Kepek Kar t ampuan 390 ml - Normal ve Ya l Sa lar', 'haircare', 'Aqua / Water, Sodium Laureth Sulfate, Glycol Distearate, Coco-Betaine, Glycerin, Dimethicone, Carbomer, CI 19140 / Yellow 5, Citric Acid, Menthol, 2-Oleamido-1,3-Octadecanediol, PPG-5-Ceteth-20, Salicylic Acid, Selenium Sulfide, Sodium Benzoate, Sodium Chloride, Sodium Hydroxide, Tocopheryl Acetate, Parfum / Fragrance.', 'Aqua / Water', '', 0, 'Vichy', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Urban Care Argan Ya & Keratin S v Sa Bak m Kremi', 'Urban Care Argan Ya & Keratin S v Sa Bak m Kremi', 'haircare', 'Aqua, Cyclopentasiloxane, Amodimethicone, PEG-40 Hydrogenated Castor Oil, Argania Spinosa Kernel Oil, Hydrolyzed Corn Protein, Hydrolyzed Soy Protein, Hydrolyzed Wheat Protein, Leuconostoc/Radish Root Ferment Filtrate, Ethylhexyl Methoxycinnamate, Polyquaternium-6, Parfum, Tetrasodium EDTA, Sodium Chloride, Cetrimonium Chloride, Trideceth-12, Citric Acid, Benzyl Alcohol, Cocamidopropyl Betaine, PPG-2 Methyl Ether, 2-Bromo-2-Nitropropane-1,3-Diol, Sodium Benzoate, Iodopropynyl Butylcarbamate, Hex', 'Aqua', '', 0, 'Urban Care', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Huile extraordinaire', 'Huile extraordinaire', 'haircare', 'ISODODECANE DIMETHICONE. DIMETHICONOL COCOS NUCIFERA OIL/COCONUT OIL. HYDROGENATED JOJOBA OIL ANISE ALCOHOL LIMONENE SIMMONDSIA CHINENSIS SEED OIL/JOJOBA SEED OIL LINALOOL. COUMARIN - HEXYL CINNAMAL PARFUM / FRAGRANCE. (F.I.L. OSTE FIXE en France', 'ISODODECANE DIMETHICONE. DIMETHICONOL COCOS NUCIFERA OIL/COCONUT OIL. HYDROGENATED JOJOBA OIL ANISE ALCOHOL LIMONENE SIMMONDSIA CHINENSIS SEED OIL/JOJOBA SEED OIL LINALOOL. COUMARIN - HEXYL CINNAMAL P', '', 0, 'L''Or al, L''Oreal Consumer products, L''Or al Paris, Elseve', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Coconut Milk', 'Coconut Milk', 'haircare', 'Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sodium Citrate, Sodium Chloride, Sodium Xylenesulfonate, Stearyl Alcohol, Parfum, Cetyl Alcohol, Glycerin, Glycol Distearate, Dimethiconol, Citric Acid, Sodium Benzoate, Dimethicone, Guar Hydroxypropyltrimonium Chloride, Hexyl Cinnamal, Tetrasodium EDTA, Sodium Hydroxide, TEA-Dodecylbenzenesulfonate, Polyquaternium-6, Trihydroxystearin, Trideceth-10, Histidine, Benzyl Salicylate, Propylene Glycol, Limonene, Linalool, Bu', 'Aqua', '', 0, 'Herbal Essences', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('ECO STYLE PROFESSIONAL STYLING GEL BLACK CASTOR & FLAXSEED OIL', 'ECO STYLE PROFESSIONAL STYLING GEL BLACK CASTOR & FLAXSEED OIL', 'haircare', 'Water/Aqua/Eau, Carbomer, Triethanolamine, Ricinus Communis (Castor) Seed Oil, Limus Usitatissimum (Linseed) Seed Oil, Hydrolyzed Wheat Protein, PVP, Glycerin, Phenoxyethanol, Polysorbate 20, Tetrasodium EDTA, Fragrance (Parfum), D-Limonene', 'Water/Aqua/Eau', '', 0, 'ECO', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Texture Paste', 'Texture Paste', 'haircare', 'Water, Acrylates Copolymer, Lanolin Wax, Stearoyl Palmitate, PEG-8 Beeswax, Steareth-21, VP/VA Copolymer, Cetearyl Alcohol, Steareth-2, PVP, Ceteareth-20, PEG-40 Hydrogenated Castor Oil, Phenoxyethanol, Fragrance, Stearic Acid, Sodium Laureth Sulfate, Aminomethyl Propanol, Disodium EDTA, Linalool, Limonene, Citral, Coumarin, Benzyl Alcohol, CI 14700, CI 19140', 'Water', '', 0, 'Cremo', 'openbeautyfacts', 'unisex', 'hair-care');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Hairspray firm hold', 'Hairspray firm hold', 'haircare', 'Use Shake can wserenly avoiding com nght approximately 2-3 ANGER essurised container: May burst f hom heat, hat surfaces, sparks and other ignition sources. FLAMMABLE AEROSOL Do not pierce or burn Protect from sunlight. se do temperatures 57 C. Do not spray on an ane or other ignition source. atafreach of children. 240 SAFETY ADVICE: Use only as directe sely to broken or irritated skin. In unie verse skin reaction, discontinue use contact with eyes. In case of contact with se immediately with cl', 'Use Shake can wserenly avoiding com nght approximately 2-3 ANGER essurised container: May burst f hom heat', '', 0, 'Superdrug', 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Cantu For Kids Conditioning Detangler', 'Cantu For Kids Conditioning Detangler', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Cantu Avocado Hydrating Styling Mousse', 'Cantu Avocado Hydrating Styling Mousse', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Mielle Rosemary Mint Strengthening Shampoo', 'Mielle Rosemary Mint Strengthening Shampoo', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Mielle Rosemary Mint Strengthening Leave-In Conditioner', 'Mielle Rosemary Mint Strengthening Leave-In Conditioner', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Aunt Jackie''s Curls & Coils Flaxseed Recipes Purify Me Moisturizing Co-Wash Cleanser', 'Aunt Jackie''s Curls & Coils Flaxseed Recipes Purify Me Moisturizing Co-Wash Cleanser', 'haircare', '', '', '', 0, 'Aunt Jacki s', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Skala Coquetel De Frutas Treatment Cream', 'Skala Coquetel De Frutas Treatment Cream', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Cantu Avocado Hydrating Conditioner', 'Cantu Avocado Hydrating Conditioner', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Cantu Avocado Hydrate Repair Leave-In Cream', 'Cantu Avocado Hydrate Repair Leave-In Cream', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Cantu Avocado Hydrating Curling Cream', 'Cantu Avocado Hydrating Curling Cream', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'hair-care');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('Cr me 3 en 1: masque, apr s-shampooing, cr me de soins sans rin age', 'Cr me 3 en 1: masque, apr s-shampooing, cr me de soins sans rin age', 'haircare', 'Aqua, Cetearyl Alcohol, Butyrospermum Parkii Butter, Behentrimonium Chloride, Cetyl Esters, Parfum, Cetrimonium Chloride, Sodium Benzoate, Citric Acid, Polyquaternium-22, Potassium Sorbate, Isopropyl Alcohol, Hydrolyzed Keratin, Panthenol, Sodium Hydroxide', 'Aqua', '', 0, 'Corinne de Farme', 'openbeautyfacts', 'unisex', 'treatment'),
  ('SheaMoisture Jamaican Black Castor Oil Shampoo', 'SheaMoisture Jamaican Black Castor Oil Shampoo', 'haircare', 'defying shampoo removes buildup, while infusing hair with nourishing moisture. Perfect for those who perly color, straighten, perm or heat style their hair, as well as kinky, curly or wavy natural styles. with Jamaican Black Castor Oil and Fair Trade Shea Butter, our Shampoo helps to promote ful hair. Use with our JAMAICAN BLACK CASTOR OIL STRENGTH & RESTORE CONDITIONER, to restore pel or chemically processed hair by reducing breakage and the resultant shedding. Peppermint Oil helps porate the s', 'defying shampoo removes buildup', '', 0, NULL, 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Cantu Guava Scalp Care Shampoo', 'Anti-dandruff shampoo', 'haircare', 'SALICYLIC ACID 3%, WATER (AQUA, EAU), SODIUM C14-16 OLEFIN SULFONATE, COCAMIDE MEA, COCAMIDOPROPYL BETAINE, FRAGRANCE (PARFUM), PSIDIUM GUAJAVA LEAF EXTRACT (GUAVA), ZINGIBER OFFICINALE (GINGER) ROOT EXTRACT, ACETIC ACID (APPLE CIDER VINEGAR), MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL, CURCUMA LONGA (TURMERIC) ROOT EXTRACT, MENTHOL, SODIUM HYDROXIDE, GUAR HYDROXYPROPYLTRIMONIUM CHLORIDE, DISODIUM EDTA, GLYCERIN, PHENOXYETHANOL, BENZOIC ACID, ETHYLHEXYLGLYCERIN, GLYCERETH-2 COCOATE', 'SALICYLIC ACID 3%', '', 0, 'Cantu', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Cantu Guava Scalp Care Conditioner', 'Cantu Guava Scalp Care Conditioner', 'haircare', '', '', '', 0, 'Cantu', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Monday Moisture Shampoo', 'Monday Moisture Shampoo', 'haircare', '', '', '', 0, 'Monday', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Monday Moisture Conditioner', 'Monday Moisture Conditioner', 'haircare', 'ke kone k m, nechte 3-5 min., pak radne opl chn te. Vyhnete se kontaktu s o ima,p i zasa en o i vypl chnete. Uchov vejte mimo dosah deti! (SK) MONDAY MOISTURE kondicion r 350ml - PRE SUCH A NAM HACH VLASY s obsahom kokos.oleja (pre hydrat ciu a lesk). hydrolyzovano ryzoveno proteinu (pre silu a objem), bambuckeho masia (pre vyzivu a zjemneniej, vitam nu E (pre zdrave vlasy aj poko ku hlavy) a provitaminu B5 (pre elasticitidu na rozstrapkan konceky). Dokonal extra v iva pre vlasy! VEGAN, bez sulf', 'ke kone k m', '', 0, 'Monday', 'openbeautyfacts', 'unisex', 'conditioner'),
  ('Monday Volume Conditioner', 'Monday Volume Conditioner', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'conditioner'),
  ('OGX Argan Oil of Morocco Haarmasker', 'OGX Argan Oil of Morocco Haarmasker', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Pantene Active Nutri-Plex Pro-V Glad & Zijdezacht Shampoo', 'Pantene Active Nutri-Plex Pro-V Glad & Zijdezacht Shampoo', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'shampoo'),
  ('SheaMoisture Coconut & Hibiscus Curl & Shine Conditioner', 'SheaMoisture Coconut & Hibiscus Curl & Shine Conditioner', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'conditioner');
INSERT OR IGNORE INTO medicines (name, generic_name, category, description, active_ingredient, dosage_form, mhra_approved, brand_names, source, gender, subcategory) VALUES
  ('As I Am Coconut Co-Wash', 'As I Am Coconut Co-Wash', 'haircare', 'Aqua/Water/Eau, Cetyl Alcohol, Cetrimonium Chloride, Cetearyl Alcohol, Cocos Nucifera (Coconut) Oil, Ricinus Communis (Castor) Seed Oil, Cocos Nucifera (Coconut) Fruit Powder, Citrus Reticulata (Tangerine) Fruit Extract, Phytosterols, Camillia Sinensis Leaf Extract, PEG-40 Castor Oil, Stearlkonium Chloride, Serenoa Serrulata Fruit Extract, Quaternium-18, Propylene Glycol, C12-15 Alkyl Lactate, Fragrance/Parfum, Potassium Sorbate, Caprylyl Glycol, Phenoxyethanol, Abies Balsamea (Balsam Canada) Re', 'Aqua/Water/Eau', '', 0, 'As I Am', 'openbeautyfacts', 'unisex', 'shampoo'),
  ('Aunt Jackie''s Oh So Clean Shampoo', 'Aunt Jackie''s Oh So Clean Shampoo', 'haircare', 'aqua, sodium c14-16 olefin sulfonate, cocamide mea, cocamidopropyl betaine, glycol stearate, glycerin, parfum, sodium chloride, polyquaternium-7, butyrospermum parkii butter, olea europaea fruit oil, tetrasodium edta, magnesium nitrate, sodium benzoate, methylchloroisothiazolinone magnesium chloride, methylisothiazolinone, citric acid d-limonene, hexyl cinnamal, linalool, amyl cinnamal, butylphenyl methylpropional, ci 15985, ci 47005', 'aqua', '', 0, NULL, 'openbeautyfacts', 'unisex', 'shampoo'),
  ('SheaMoisture Manuka Honey & Mafura Oil Intensive Hydration Masker', 'SheaMoisture Manuka Honey & Mafura Oil Intensive Hydration Masker', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'hair-care'),
  ('Syoss Intense Keratin Deep Caring Shampoo', 'Syoss Keratin Shampoo herstelt breekbaar haar. Natuurlijke ingredi nten gecombineerd met het aminocomplex dragen bij aan sterk en gezond haar.', 'haircare', '', '', '', 0, NULL, 'openbeautyfacts', 'unisex', 'shampoo');
